### ISSUE TITLE
Setup on iPad Pro 3rd Generation

### ISSUE THREAD

**Issue by alanmsings** [hymns-for-worship/issues#10]
I purchased the Hymns for Worship app this Sunday and installed it on my iPad Pro 3rd Generation. However, none of the hymn sheet music, slides, or other song information downloaded to my iPad Pro. I have created an account and logged in and was unable to download any song information nor sheet music.

**Comment by rodydavis** [comment]
Can you check on the latest? Im also waiting on Apple to approve the latest update

**Comment by rodydavis** [comment]
Please reopen if you are still having issues
