### ISSUE TITLE
HFW Studio store images and load file sheet download not working properly

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#100]
I searched for 1 hymn, selected for download, downloaded the zip for the store images and for the WooCommerce load file (attached) and it has 3 hymns  - that are not the hymn I selected.   This happens for other hymns I searched for (like 21785 -  not a new hymn) See screenshots.  

<img width="1440" alt="image" src="https://github.com/hymns-for-worship/issues/assets/10003118/6781dd9f-5db8-4086-b89e-da58d23d07b3">

<img width="1286" alt="image" src="https://github.com/hymns-for-worship/issues/assets/10003118/b73c0895-b5ff-4c4b-a14e-822aa35b3ef3">

[woo_commerce.xlsx](https://github.com/hymns-for-worship/issues/files/14731277/woo_commerce.xlsx)

**Comment by ebizman** [comment]
@rodydavis - any estimate on when this will be fixed?  I checked today and it is still an issue.  Also did not see this item moved to your kanban.

**Comment by ebizman** [comment]
Note that the hymn bundle download also does not work (tested 21911).  Attempted to download slides, sheet music PDFs- no luck.  Was able to download the title slide PPT.

**Comment by rodydavis** [comment]
Looking into this and testing with this song.

**Comment by rodydavis** [comment]
<img width="286" alt="Screenshot 2024-03-31 at 2 16 35 PM" src="https://github.com/hymns-for-worship/issues/assets/31253215/a8df4c4b-5582-4f88-a2f7-26cb0fa80681">
<img width="927" alt="Screenshot 2024-03-31 at 2 16 47 PM" src="https://github.com/hymns-for-worship/issues/assets/31253215/a9bb7e76-ea94-408d-b7c0-c17b2854890a">
<img width="842" alt="Screenshot 2024-03-31 at 2 16 09 PM" src="https://github.com/hymns-for-worship/issues/assets/31253215/c9042f42-5851-4f7c-a74a-abe342f88459">

21911 worked for me. The download url opens in a new tab then downloads. It may take a second to load.

**Comment by ebizman** [comment]
Was using Safari on MacOS.  -RhettOn Mar 30, 2024, at 10:18 PM, Rody Davis ***@***.***> wrote:﻿
Screenshot.2024-03-31.at.2.16.35.PM.png (view on web)
Screenshot.2024-03-31.at.2.16.47.PM.png (view on web)
Screenshot.2024-03-31.at.2.16.09.PM.png (view on web)
21911 worked for me. The download url opens in a new tab then downloads. It may take a second to load.

**Comment by rodydavis** [comment]
The admin tool is built to work with any chromium based browser. The app supports more, but for back office tool I can only support 1.

**Comment by ebizman** [comment]
Ok - was not aware - perhaps add a message or something?    Also, should desktop (assume more practical) chrome be used vs mobile? -RhettOn Mar 30, 2024, at 10:24 PM, Rody Davis ***@***.***> wrote:﻿
The admin tool is built to work with any chromium based browser. The app supports more, but for back office tool I can only support 1.

**Comment by rodydavis** [comment]
Oh the admin app is only meant for desktop (basic features might work on mobile though).

Adding a message is a good call!

<img width="895" alt="Screenshot 2024-03-31 at 2 46 13 PM" src="https://github.com/hymns-for-worship/issues/assets/31253215/3a29f977-3957-49ab-ad13-63aae911e3ef">

Also fixed an issue with the 'generate bundle" for store images and should be working now.
