### ISSUE TITLE
Formatting of hymn title slides is messed up

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#101]
<img width="1440" alt="image" src="https://github.com/hymns-for-worship/issues/assets/10003118/dbf53bc6-82b3-47f2-953c-073df174217a">

**Comment by rodydavis** [comment]
This is now resolved:

<img width="831" alt="Screenshot 2024-03-31 at 2 11 59 PM" src="https://github.com/hymns-for-worship/issues/assets/31253215/55429db3-b8dc-4128-8eba-f6f99289250a">
