### ISSUE TITLE
Exporting pptx on Mac results in corrupt file

### ISSUE THREAD

**Issue by timeighty5** [hymns-for-worship/issues#102]
When exporting a playlist from the app (v. 3.0.7+761) and opening on Powerpoint for Mac (v 16.83) a prompt appears that the file is corrupt and needs repairing. The repair seems to be successful each time I've tried.

Mac OS Sonoma v 14.3

<img width="259" alt="Screenshot 2024-03-23 at 10 05 56 PM" src="https://github.com/hymns-for-worship/issues/assets/6557332/3b041a24-4dac-4e4c-9c97-17d660b0b258">
<img width="257" alt="Screenshot 2024-03-23 at 10 06 06 PM" src="https://github.com/hymns-for-worship/issues/assets/6557332/d757fdb3-dd38-4511-8fde-9c1d82e97fa0">

**Comment by rodydavis** [comment]
This was happening to me too, looking into the issue, but not getting any errors or reasons why it is corrupt. 

Working on a trial and error way of making one change at a time to see if I can get the error removed.

**Comment by MitchellH79** [comment]
I get the same error message & have been for at least several months

**Comment by rodydavis** [comment]
Can you test with https://hymnsforworship.app?

Version 4 is out and should fix it

**Comment by MitchellH79** [comment]
I just posted on another thread regarding login issues, but no I cannot try thru the web app due to not being able to log in with my Apple ID.  here is the error I'm getting

![Screenshot 2024-07-15 at 2 16 46 PM](https://github.com/user-attachments/assets/f91ba40e-ed5a-41f4-9925-fcfebbc31298)

**Comment by rodydavis** [comment]
Apple and Google login are no longer supported due some issues that were out of my control. Login to the app with the email for the Apple ID.

It will stay logged in for a long time.

**Comment by MitchellH79** [comment]
Ok but how to i get my subscription thru the Apple ID routed over to it?  I saw the link for signing in with apple was gone so i used my email associated with Apple ID. I then used my Apple ID password.  Am i needing to create a new account or something?

**Comment by MitchellH79** [comment]
I reset password and am able to log in but its not loading my pro subscription![image](https://github.com/user-attachments/assets/c74e524c-6211-4812-9de2-ccd00ce6d892)

**Comment by rodydavis** [comment]
Click on restore purchases and it should sync the purchases and active subscriptions to the server.

Also in your iCloud subscriptions view does it show the pro subscription as being active?

**Comment by MitchellH79** [comment]
I've tried restoring the purchases several times, on each of the browsers i mentioned above. I assume you mean clicking on the icon in the top right of the picture, correct?  I also tried checking the box for "purchases enabled" but that doesnt seem to do anything.

Yes, Apple shows my subscription as the Pro plan![image](https://github.com/user-attachments/assets/702519ab-c616-4fb8-9d7f-b8389c4987d9)![image](https://github.com/user-attachments/assets/6823214c-e1cf-450b-917d-634a27276670)

**Comment by rodydavis** [comment]
Can you screenshot the app purchases tab?

**Comment by MitchellH79** [comment]
Is this what you're looking for?
![image](https://github.com/user-attachments/assets/ab2b9daa-4c0a-4205-9783-6dc36c210188)

![image](https://github.com/user-attachments/assets/4c68a4f1-cf32-4fc2-b04b-5e860b2562eb)

**Comment by rodydavis** [comment]
You should be seeing a "restore purchases" button at the bottom?

**Comment by MitchellH79** [comment]
Yes ive tried that lots of times in the past, as recently as this past friday night, without it updating to show my pro subscription.  BUT im guessing something changed since then or the planets all finally aligned b/c in the last 10 minutes if gotten it to work on my iPhone & on MacOS. 

Thank you!!!

**Comment by rodydavis** [comment]
Right on!
