### ISSUE TITLE
Music will not display in IOS and Android app.

### ISSUE THREAD

**Issue by JohnEMSammons** [hymns-for-worship/issues#103]
When music is downloaded switching to the music tab immediately closes application (crash).

ios v3.2.0+766 iPadOS 17.4

Android v3.2.0+766 Android V14

**Comment by rodydavis** [comment]
This is because older bundles had images that were to big to load in memory. The recent versions should fix this

**Comment by rodydavis** [comment]
Fixed on version 4.0.0
