### ISSUE TITLE
UPDATES

### ISSUE THREAD

**Issue by DSCOBURN** [hymns-for-worship/issues#104]
Rody
Songs that need to Updating
21821
21856
21865
21876
21971
1083
1102
1073
21845
21874
21836

**Comment by rodydavis** [comment]
Did you mark them as stale?

**Comment by DSCOBURN** [comment]
Yes. I made them after I changed the files. Steve Coburn 251 Richardson Rd. Columbus, MS. ***@***.*** Mar 30, 2024, at 10:13 PM, Rody Davis ***@***.***> wrote:﻿
Did you mark them as stale?
