### ISSUE TITLE
Unable to login via Apple

### ISSUE THREAD

**Issue by Csprinkel** [hymns-for-worship/issues#105]
Been trying to log in but have not been able to for a few weeks. When I click on “Sign in with Apple”, I go to a different screen and I use my thumbprint on my iPad and I get the message that states Auth Complete.  I go back to the app and it says “Something went wrong when processing your request.”

**Comment by MitchellH79** [comment]
Ditto, however I'm able to sign-in on iOS & ipadOS but not on anything else.

**Comment by rodydavis** [comment]
I am removing SSO and social sign in on all platforms due to some issues outside of my control.

I made the token sign in for the user last for at least 90 days now.

Cleaned up the auth flow in the app and you can test on the web version now.

**Comment by MitchellH79** [comment]
I'm trying to login with the email address & password associated with my Apple ID but getting this error.  I have tried Chrome, Safari and Edge.   
![Screenshot 2024-07-15 at 2 16 46 PM](https://github.com/user-attachments/assets/e0f32070-c15f-4f89-bc9d-9fa500a68de7)

**Comment by rodydavis** [comment]
It's not your Apple ID password but password for the. You can reset the password easily!
