### ISSUE TITLE
WOO worksheet

### ISSUE THREAD

**Issue by DSCOBURN** [hymns-for-worship/issues#106]
Rody
On the Woo Commerce files 

I swapped some of the columns around from the one that was printed

Column I – HymnStatus needs to map from hymn/category id

Columns O, P, Q should be rjsec21819 not rjcec21819

Column Z – Download URL needs to map from hymn/Download link  https://hymns-for-
worship.fra1.cdn.digitaloceanspaces.com/bundles/s0er92h1bo7ec21.zip

Column AC Verse text – needs to have <br/> for page breaks between verses

**Comment by rodydavis** [comment]
This should be fixed now
