### ISSUE TITLE
Exporting to PowerPoint issues 

### ISSUE THREAD

**Issue by Logan323212** [hymns-for-worship/issues#107]
We have had multiple issues exporting to PowerPoint.
One of the bigger issues is that whenever the slides are exported to PowerPoint they appear all mixed up.
Sometimes when we drop the slides into PowerPoint it looks like PowerPoint will attempt to "repair " the slides and this seems to be when the issue of missing or mixed up slides appears.
This seems to be an isolated issue meaning this only happens when we use the new HFW app.

**Comment by rodydavis** [comment]
Repair is normal, still investigating what is causing it. Not causing an error for Linux or macOS
