### ISSUE TITLE
Playlist URL does not work - need a way to share a simple text list of hymns

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#109]
https://hymnsforworship.app/#/users/47i17sr8qiuan5l/playlists/000000IWQ93f-8H

Just a text list with the hymn number and title to share via text or email is what we need - saving PPT or PC or HTML is not easy to text someone.  Also please remove the pre-filled "Playlist" in the playlist name field because you have to backspace / select - either remove or clear when you tap in the field or provide an X to clear the field.

**Comment by rodydavis** [comment]
You can share with markdown! It is a textual representation of the hymns like you want!

**Comment by rodydavis** [comment]
For the name field I can add an easy clear button 👍🏼

**Comment by ebizman** [comment]
Users are just wanting a simple text list to share, not markdown.

**Comment by rodydavis** [comment]
Markdown is text, but I am going to add an option off by default to add the links
