### ISSUE TITLE
Login on anything but iOS & iPadOS

### ISSUE THREAD

**Issue by MitchellH79** [hymns-for-worship/issues#110]
I have the pro subscription and am able to sign in on both my iPads & iPhone but cannot get signed in thru any browser, on Windows, or on MacOS.

I have tried typing in my AppleID & PW there in the app and have tried using the "Sign in with Apple" option.  No luck on either. 

 ![image](https://github.com/hymns-for-worship/issues/assets/156945904/6214067d-3e2f-45a1-85b8-58d491220cc3)![image](https://github.com/hymns-for-worship/issues/assets/156945904/53c4adbf-264f-4b3a-a1b6-c06e93a28641)![image](https://github.com/hymns-for-worship/issues/assets/156945904/ef1454a7-1059-4cb5-9f26-d9c92dc8a011)

**Comment by rodydavis** [comment]
Login is changing for the better, and fixed on version 4.0.0 of the app

**Comment by MitchellH79** [comment]
you say "login is changing..." does that mean it is still in the works?  hymnsforworship.app is showing to be 4.0.0 but it still isn't loading my pro subscription.  

On all 3 of the Account Purchases tabs there is a white horizontal bar scrolling across the window but nothing ever changes.  I have tried logging out and back in without any luck.

**Comment by rodydavis** [comment]
Make sure on the web app it is at least on version 4.1.0 and then on the mobile app click restore purchases.

The white loading bar issue is now fixed on Android/iOS and also patched for the web.

If you don't have 4.1.0 from the beta it will be on the live version soon in the next few days for iOS and Android.
