### ISSUE TITLE
Playlist Functionality is Down

### ISSUE THREAD

**Issue by cjbarker549** [hymns-for-worship/issues#114]
I went to my account to look at past created playlists, and there’s a blank screen

**Comment by rodydavis** [comment]
Which version of the app? You can see the number in settings

**Comment by cjbarker549** [comment]
Looks like it’s 3.2.0+766.

Also, when I go to create a new playlist, I see this error:

**Comment by rodydavis** [comment]
Version 4.0.0 fixes this and rolls out this week!

**Comment by cjbarker549** [comment]
Sounds great, thank you!

**Comment by cjbarker549** [comment]
Thank you Rody!

Also, I just wrote another issue about logging in. Aside from that though,
I’m willing to help be a contributor to the ongoing development of the app.
I test software for a living and can help find issues. With some training,
I could also help contribute to some fixes and such.

I have another friend who’s also interested in contributing and is better
with development than I am. We go to the same church and use the app with
preparing songs for Sunday mornings. We enjoy the access the app gives us
to more songs, and we’d like to help with fixing issues and helping make
the app better!

Let me know what you think! Thanks for your work -Christopher

**Comment by rodydavis** [comment]
That's really amazing! Please DM me on the discord!
