### ISSUE TITLE
Trouble with Login Authentication 

### ISSUE THREAD

**Issue by cjbarker549** [hymns-for-worship/issues#115]
When I try to log in the the Hymns for Worship app, I run into some authentication errors: (hopefully the image loads)

![image](https://github.com/user-attachments/assets/a43fd492-acfa-4bc5-a605-cbcc98b8a2c0)

![IMG_3242](https://github.com/user-attachments/assets/584411e5-def0-4307-8c3b-091ecce5ac68)

this happens both on the Apple phone app version 4.0.0 and the desktop client downloaded from the Windows store.

**Comment by rodydavis** [comment]
That error usually means incorrect username or password!

**Comment by cjbarker549** [comment]
Hmm interesting, we entered in our usual email and password and it still
hasn’t worked!

I wonder….in the older versions, we would do the “sign in with Google”
method, but I don’t see that option in the newer version. I wonder if that
workflow would cause the email bro be recognized with an account, while not
saving the password in your database

**Comment by rodydavis** [comment]
Try resetting the password!

**Comment by cjbarker549** [comment]
that worked for signing in. Still running into some bugs restoring
purchases on my WIndows PC app, but able to restore purchases on my phone
and access things. Thanks!

**Comment by rodydavis** [comment]
For restoring purchases make sure to restore them on Android or iOS first before windows!
