### ISSUE TITLE
PowerPoint App iOS Can't Open .PPTX Export

### ISSUE THREAD

**Issue by alanmsings** [hymns-for-worship/issues#117]
![image](https://github.com/user-attachments/assets/2f5b20d1-f5f4-488e-b9f8-59feba61c25f)

**Comment by alanmsings** [comment]
The iOS PowerPoint App presents this error message when opening downloaded presentations.

**Comment by rodydavis** [comment]
Which iOS version and which app version? It is working for me

![image](https://github.com/user-attachments/assets/40af46f3-fd20-42cd-a4eb-f28861261057)

**Comment by alanmsings** [comment]
When I originally posted this, I was on an earlier version of iOS and Hymns for Worship. It is still occurring. I am on iOS 18 and Hymns for Worship 4.6. To work around this issue, I open the PowerPoint in Keynote then export it in PowerPoint format, then I open it in PowerPoint without any issue. This also happens in the Windows version of Hymns for Worship. In Windows, PowerPoint gives you the option to repair the PPTX file which allows it to open in PowerPoint without the error message.

**Comment by rodydavis** [comment]
Maybe that is why I was not seeing this since I always open in keynote first!

I will see if I can get it working for windows though
