### ISSUE TITLE
HFW Folder Disappeared After Updates

### ISSUE THREAD

**Issue by alanmsings** [hymns-for-worship/issues#118]
The Hymns for Worship folder in the Files app on my iPhone disappeared after the latest updates. I saved all my presentations in this folder. Did the updates delete this folder or is it hidden within the Files app?

**Comment by rodydavis** [comment]
I didn’t know the folder was there to begin with! Nothing changed about how to export, but it will be some where in the files apps.

I’ll look into future updates to see if I can make the folder reappear
