### ISSUE TITLE
Added fuzzy search on all lists, should help with this case!

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#120]
Added fuzzy search on all lists, should help with this case!

_Originally posted by @rodydavis in https://github.com/hymns-for-worship/issues/issues/28#issuecomment-1462389970_

Still not working - main search bar does not return any hymns for any text search.  Text search should hit title, scripture, topic, etc fields and return a matching list of hymns.

**Comment by rodydavis** [comment]
Can you upload a video? It was working for me

**Comment by ebizman** [comment]
I probably can download a screencap app but this is real simple - type any term, return and then nothing: -RhettOn Aug 14, 2024, at 4:34 PM, Rody Davis ***@***.***> wrote:﻿
Can you upload a video? It was working for me

**Comment by ebizman** [comment]
Ok, this must be a bug as I closed the app and then opened it again and tried and now search is working.  Only thing I was doing in the app was building some lists

**Comment by rodydavis** [comment]
Sounds good, so just need to do some smoke tests then to see what gets it in that state

**Comment by ebizman** [comment]
Search for SKU is still not working: 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/759f5448-0381-4142-bffd-efdc2c95ba91">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b3f7e560-dd20-48b3-abb6-04d318eed944">

**Comment by rodydavis** [comment]
Since the SKU is the number I would suggest using an explicit filter till it rolls out

![image](https://github.com/user-attachments/assets/96e07b8b-26ce-4aff-8bfe-a17d164f9b22)

**Comment by ebizman** [comment]
Searching for SKU using a filter against the Number field also does not
work:

[image: image.png]

**Comment by rodydavis** [comment]
Image is not loaded, you need to attach on GitHub directly on the issue.

But I was meaning searching the number part of the SKU since it is the number:

RJSEC1002 -> 1002

Then you can do an exact number search. Most users will not need to search by SKU but happy to still add it if it helps.

**Comment by ebizman** [comment]
Oh, ok.  I misunderstood - thought you had enabled full text search against all fields.  -RhettOn Aug 24, 2024, at 8:22 AM, Rody Davis ***@***.***> wrote:﻿
Image is not loaded, you need to attach on GitHub directly on the issue.
But I was meaning searching the number part of the SKU since it is the number:
RJSEC1002 -> 1002
Then you can do an exact number search. Most users will not need to search by SKU but happy to still add it if it helps.

**Comment by rodydavis** [comment]
It's full text search on all fields but the app does not display the SKU so I only return the fields relevant to the app.

So the number of id would be the way to search for a hymn if you have an exact value.

Also using a filter will give much better results if you are trying to be specific. The full text search is really more for lyrics and topics and getting better results there.

**Comment by rodydavis** [comment]
Fixed on the latest!

**Comment by ebizman** [comment]
Still requires commas when there are commas in the title - experienced that tonight  -RhettOn Oct 29, 2024, at 7:58 PM, Rody Davis ***@***.***> wrote:﻿
Fixed on the latest!

**Comment by rodydavis** [comment]
Can you try on the web and windows? That has the new version that will roll out

**Comment by ebizman** [comment]
yes!   a bit slow, but it works now!
