### ISSUE TITLE
"Favorite" hymns disappeared in last release

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#121]
Spent a lot of time creating a pick list of favorite hymns and they have disappeared. Cannot find any favorites list now at all in the app - only playlists (I will now create a new playlist for favorites if this is the new way but it is inconvenient and impactful to users of the app.)

**Comment by rodydavis** [comment]
Started migrating the lists today, you should see it pop up on your playlists soon.

**Comment by rodydavis** [comment]
All favorite lists migrated
