### ISSUE TITLE
Markdown is text, but I am going to add an option off by default to add the links

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#124]
Markdown is text, but I am going to add an option off by default to add the links

_Originally posted by @rodydavis in https://github.com/hymns-for-worship/issues/issues/109#issuecomment-2289413151_

**Comment by rodydavis** [comment]
Fixed on the latest! (For presentation creator)

**Comment by ebizman** [comment]
This is mostly needed for the app so that songleaders can easily text or email their hymn list to sound booth folks.  -RhettOn Oct 29, 2024, at 7:57 PM, Rody Davis ***@***.***> wrote:﻿
Fixed on the latest! (For presentation creator)
