### ISSUE TITLE
Add Hymn in Playlist

### ISSUE THREAD

**Issue by alanmsings** [hymns-for-worship/issues#125]
The "Add Hymn" button in the playlist feature is not working. It is unresponsive when pressed.

**Comment by rodydavis** [comment]
Is this still happening?
I have tested on web and it is working for me:
https://hymnsforworship.app

**Comment by alanmsings** [comment]
In the iOS app it is still happening. I have not tested it on the web or Windows app.

**Comment by alanmsings** [comment]
Safari and Chrome in iOS iPhone 14+ add hymn to playlist does not work for me.

**Comment by rodydavis** [comment]
Can you test on a desktop browser? Just to rule it out for your account
