### ISSUE TITLE
Hymns not downloading

### ISSUE THREAD

**Issue by USER2749506** [hymns-for-worship/issues#127]
Hymns are not downloading with latest update while connected to server.  I already updated library.

**Comment by rodydavis** [comment]
Is this still happening?

Does it also happen on web?
https://hymnsforworship.app

**Comment by USER2749506** [comment]
Hi Rody,

Thank you for checking on this issue.

Website is ok, but the app for Mac is not downloading. Every time I click download, app will say the hymn is not available.

Let me know if you need anything else.

Hai

**Comment by rodydavis** [comment]
Mac version is broken at the moment. Working with Apple on trying to get the update out for v4

**Comment by USER2749506** [comment]
Good morning, RodyThank you for updating me. Warm Regards,Hai PhamOn Sep 7, 2024, at 10:05 PM, Rody Davis ***@***.***> wrote:﻿
Mac version is broken at the moment. Working with Apple on trying to get the update out for v4
