### ISSUE TITLE
PC mode: Expert entry is hymn number is < 3 digits

### ISSUE THREAD

**Issue by bryanellismil** [hymns-for-worship/issues#129]
If you enter "63" it should assume "063" or "1" should assume "001". Right now it does not add the song to the list at all and skips it. For example, expert entry of:
63;b:Scripture Reading   Psalm 54;b:Prayer;167:123;b:Communion;b:Collection;397;276;b:Announcements;b:Prayer
worked EXCEPT that it skipped the first song.

**Comment by rodydavis** [comment]
Should be fixed on the latest!
