### ISSUE TITLE
Ability to create a Playlist immediately in PC mode OR default via settings to PC mode

### ISSUE THREAD

**Issue by bryanellismil** [hymns-for-worship/issues#131]
Could we add a button when creating a playlist to jump straight to PC mode and/or possibly add an app-level setting for defaulting to PC mode? I, for one, will ALWAYS enter playlists using Expert Mode Entry. Any other method is drastically slower if the songs have already been picked out and I know the numbers - especially when text slides need to be included in specific places.
Could also be that on the playlist screen we could have an expert mode text box somewhere so if you type in it and hit ENTER it immediately creates a new playlist with those selections in it.

**Comment by rodydavis** [comment]
This will be the case on the next version!

It should already be live for web/windows.
