### ISSUE TITLE
Every PPT created is corrupt; must save a copy after PPT deletes corrupt data

### ISSUE THREAD

**Issue by AlphaMikeDelta** [hymns-for-worship/issues#132]
Every PPT created is corrupt. Using Windows 11, PowerPoint in Microsoft Office 365. 
After Hymns for Worship creates the PPT, opening the file in PowerPoint gives an error message that there are corrupt elements in the file. PowerPoint removes the corrupt elements, but the same error message is displayed after the file is saved and reopened. The file must be saved as a copy under a new name.

**Comment by rodydavis** [comment]
It's ok that it is corrupt and can be repaired. I am looking into it, but it works on Mac and Linux perfectly. It's a windows specific thing but will be fixed at some point
