### ISSUE TITLE
Hymn #343 Let Him Have and #41 Light The Fire

### ISSUE THREAD

**Issue by Lawrente1** [hymns-for-worship/issues#134]
When I attempt to add these hymns to my Playlist from within the playlist, other random Hymns are added to the playlist. It will add if I go into the hymn, then add to the playlist that way.

**Comment by rodydavis** [comment]
Can you share a screen record?

**Comment by rodydavis** [comment]
Also what were the hymns before and after?

**Comment by Lawrente1** [comment]
Here's the screenshot for 343 Let Him Have His Way With Thee.  I was having trouble with 041 Light the Fire in the desktop version of the Presentation Creator.Sincerely,Troy Lawrence8238 Pioneer OakConverse, TX ***@***.***@***@***.***@***@***.***: Rody Davis ***@***.***>Sent: Monday, September 23, 2024 6:03:00 PMTo: hymns-for-worship/issues ***@***.***>Cc: Lawrente1 ***@***.***>; Author ***@***.***>Subject: Re: [hymns-for-worship/issues] Hymn #343 Let Him Have and #41 Light
 The Fire (Issue #134)
Also what were the hymns before and after?

**Comment by rodydavis** [comment]
You will need to upload the screenshot directly on GitHub. It did not attach for me

**Comment by Lawrente1** [comment]
![Screenshot_20240923_180609_Chrome.jpg](https://github.com/user-attachments/assets/caba3de8-e31c-4815-8468-1347f4265caf)

**Comment by rodydavis** [comment]
Thank you!

**Comment by DSCOBURN** [comment]
“Light the Fire” is a supplement song. Those songs are four digit as 1041. Add a 10 or a 1 to make them four digit.
