### ISSUE TITLE
BETA 4.1 Issue

### ISSUE THREAD

**Issue by dkladd** [hymns-for-worship/issues#138]
Hey Rody! I've been working through the app today and found a couple of things you might want to look at. 

When using Presentation Creator on the iPad, I can't scroll using touch if I do an Expert Hymn Search that brings up a lot of results. I can scroll using an attached keyboard on the iPad but touch won't work. See the attached picture. 

Also, when I search for a song in expert mode using lyrics, it won't pull the song I'm looking for. For example, I searched "when peace like a river" expecting to pull up It Is Well, but it didn't pull anything.

Not sure if this is a bug or an enhancement request but in the legacy version of Presentation Creator, when you search for lyrics in expert mode, it will highlight the word in yellow you're searching wants it find a match in the specific song. Is it possible to do the same thing in the app? 

I'll keep looking and let you know what else I find. Let me know if I need to clarify anything. Thanks! 

![image](https://github.com/user-attachments/assets/d652721b-b64c-4ac6-85ef-0df3b8fcc641)

**Comment by rodydavis** [comment]
Thanks for letting me know!

**Comment by dkladd** [comment]
I downloaded the 4.5.2 from the App Store and I'm still unable to scroll using my finger on the iPad. Are you experiencing the same issue in your use?

**Comment by rodydavis** [comment]
Oh can you do two finger scroll?

**Comment by dkladd** [comment]
Didn't think to do that the first time haha. It did work when I did that. Do you think it would be helpful to change it to a single finger slide instead of two? I'm concerned users won't know to try a two finger scroll but then again it could have just been me 😂

**Comment by rodydavis** [comment]
On the latest I made it so only on desktop it does not require long press!
