### ISSUE TITLE
Having Issues with the program across all platforms. It is not showing any of the hymns.

### ISSUE THREAD

**Issue by preaching2man** [hymns-for-worship/issues#14]

**Comment by rodydavis** [comment]
Serious server issue, update will be deployed soon!

**Comment by preaching2man** [comment]
Thank you. I am still having issues with functionality. Hymns not showing online or on the desktop app. I can see the hymns on the iphone app, but when trying to add to a presentation or go to the presentation screen, it shows a blank screen and will not allow me to do it. See attached video.

https://user-images.githubusercontent.com/118376922/206776987-cb61f644-41aa-46fa-84ce-08916208416d.MP4

ed video

**Comment by rodydavis** [comment]
Just pushed out a beta for testing. If all goes well, will roll to production!

**Comment by rodydavis** [comment]
Now in production!

**Comment by rodydavis** [comment]
This has been fixed, but please open a new issue if there are still problems!
