### ISSUE TITLE
Need to pass a string list to the PocketBase picker 

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#141]
Please see if you can do something with PocketBase so that multiple product IDs can be fetched / selected using the picker (for both Quickbooks and WooCommerce - had mentioned this a while back) - it is very tedious to search / pick hymns one at a time for building load files - the computer should be able to do this for us.   See:  

<img width="948" alt="image" src="https://github.com/user-attachments/assets/051391c7-403a-41c5-b4b9-500ecad4851f">

**Comment by rodydavis** [comment]
I can send the feature request on to PocketBase and see if there is an easy way to do this 👍🏼

**Comment by rodydavis** [comment]
You can do something like this:

`number = '102' || number = '103'`

![image](https://github.com/user-attachments/assets/692fcc1f-e2f9-4d92-9d4a-caf3d26c9ca3)
