### ISSUE TITLE
Error searching for hymn

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#143]
The app is also not auto hiding the keyboard at the bottom and you have to force quit the app to get to the menu items on the bottom of the app.  I can't do a screen capture because you are restricting that.  Was searching for "I'd rather have Jesus":

Error loading hymns:
SqliteException(1): while preparing statement, unrecognized token: "'I'')) OR "hymns"."title" LIKE ?) AND "hymns"."status" IN (?, ?) ORDER BY "hymns"."number" ASC LIMIT 100 OFFSET 0;", SQL logic error (code 1)
  Causing statement: SELECT * FROM "hymns" WHERE ("record_id" IN (SELECT "hymn_portions"."hymn_id" AS "hymn_portions.hymn_id" FROM "hymn_portions_fts" INNER JOIN "hymn_portions" ON hymn_portions_fts.rowid = hymn_portions.id WHERE "hymn_portions"."hymn_id" = "hymns"."record_id" AND (hymn_portions_fts MATCH 'I'')) OR "hymns"."title" LIKE ?) AND "hymns"."status" IN (?, ?) ORDER BY "hymns"."number" ASC LIMIT 100 OFFSET 0;

![image](https://github.com/user-attachments/assets/63a11eba-d875-4dfb-9cc2-842423973257)

**Comment by rodydavis** [comment]
Thank you! Will show an error, search should not be able to include special characters

**Comment by rodydavis** [comment]
This is fixed now on the latest (web) and will roll out to mobile and desktop next.
