### ISSUE TITLE
Unable to Export Playlist to PowerPoint After Update to 4.6 iOS

### ISSUE THREAD

**Issue by alanmsings** [hymns-for-worship/issues#146]
I'm unable to export a Playlist to PowerPoint after the update to 4.6 on iOS. Please review the screenshot below.

![image](https://github.com/user-attachments/assets/e52b9f0f-7c7b-451b-8a63-5022c07c595b)

**Comment by DSCOBURN** [comment]
![Screenshot (8)](https://github.com/user-attachments/assets/6658e492-79b5-4d35-8f8e-d6e524865456)
click the in the square with arrow top left.

**Comment by rodydavis** [comment]
You should click "Save file" button, and it is working for me!

**Comment by alanmsings** [comment]
I am experiencing a delay / lag before those options display. I have full connection to the Internet. What would cause the delay?

**Comment by rodydavis** [comment]
The delay is because it stops the UI thread since it is doing it all offline. The delay is expected and there should be a text label showing it is normal!

**Comment by rodydavis** [comment]
![image](https://github.com/user-attachments/assets/c585043c-3957-43d9-9cf1-5d50a2ac4f6d)

**Comment by alanmsings** [comment]
I understand. Thank you. A new, but related, issue has emerged. When changing the transition to No Transition, clicking on the transition drop down menu does not work. I have to click the back arrow to go back to the export options menu, click PPTX, then select No Transition. The progress bar indicates the PPTX is attempting to export but it seems to be stuck. The download button doesn't work.

![image](https://github.com/user-attachments/assets/50072740-7036-4be8-811a-567dc7ed929e)

**Comment by rodydavis** [comment]
Noted! And the download icon is only for presentation. There will be a "Save file" button when it is done.

I will see if I can fix changing transitions so it regenerates the presentation.
