### ISSUE TITLE
Cannot access purchased subscriptions 

### ISSUE THREAD

**Issue by Miller6288** [hymns-for-worship/issues#149]
I purchased the E-Choice annual pass in May 2024.  Now, I can’t access my subscription.  When I hit ‘Renew Purchases,’ I get a long error stating the Apple purchase key is unacceptable.  It is Platform Exception 17.  I have attached a screenshot of the error.
![IMG_4530](https://github.com/user-attachments/assets/0851952c-dc14-4115-8bff-9501678af523)

**Comment by rodydavis** [comment]
Thank you for reporting! Looking into it

**Comment by Miller6288** [comment]
Thanks for the quick reply.  The same thing is happening to my son.


Sent from AT&T Yahoo Mail for iPhone


On Saturday, December 28, 2024, 1:03 PM, Rody Davis ***@***.***> wrote:




Thank you for reporting! Looking into it

**Comment by rodydavis** [comment]
What iOS or Android versions? And what is the version number in the app (settings)?

**Comment by rodydavis** [comment]
Saving this link for me later:

https://www.revenuecat.com/docs/service-credentials/itunesconnect-app-specific-shared-secret/in-app-purchase-key-configuration

**Comment by Miller6288** [comment]
IOS 18.1.1Where do I find the app version?  I see a change log, but I don’t see a version listed anywhere else.


Sent from AT&T Yahoo Mail for iPhone


On Saturday, December 28, 2024, 3:14 PM, Rody Davis ***@***.***> wrote:




What iOS or Android versions? And what is the version number in the app (settings)?

**Comment by rodydavis** [comment]
Settings tab!

![image](https://github.com/user-attachments/assets/5ad413e0-37f7-4c40-a5e3-c9f5bfd2b4bb)

**Comment by Miller6288** [comment]
I have version 4.6.0+863


Sent from AT&T Yahoo Mail for iPhone


On Saturday, December 28, 2024, 3:56 PM, Rody Davis ***@***.***> wrote:




Settings tab!

525A664F-A6EC-4134-AF6E-316DF1E7FAF6.jpeg (view on web)

**Comment by rodydavis** [comment]
Thank you!

**Comment by meadows8654** [comment]
Having the same issue, for weeks now. Same iOS version and changelog version.

**Comment by rodydavis** [comment]
Working on a fix!

**Comment by Miller6288** [comment]
Any progress?  We were planning on using the App slides for a get together at our house tonight.
Thanks.


Sent from AT&T Yahoo Mail for iPhone


On Sunday, December 29, 2024, 10:21 AM, Rody Davis ***@***.***> wrote:




Working on a fix!

**Comment by rodydavis** [comment]
Still trying to get it resolved

**Comment by rodydavis** [comment]
Should be updated on the backend now, please test to see if it is resolved for you!

**Comment by meadows8654** [comment]
That worked! Thank you and happy New Year!

**Comment by rodydavis** [comment]
Thank you! Happy new year!

**Comment by Miller6288** [comment]
Worked for me too.  Thanks so much for your timely work on this!  Happy New Year!


Sent from AT&T Yahoo Mail for iPhone


On Tuesday, December 31, 2024, 11:50 AM, meadows8654 ***@***.***> wrote:




That worked! Thank you and happy New Year!
