### ISSUE TITLE
Menu buttons result in blank pages

### ISSUE THREAD

**Issue by headmasterditto** [hymns-for-worship/issues#15]
Video provided demonstrates me trying to access the Top Songs, Public Playlist, Profile Playlist, and Presentation menus, all leading to a blank, gray screen. The video was taken on my iPad (16.1), but also occurs on iPhone (also 16.1) and on the web app.

https://user-images.githubusercontent.com/44350163/204147774-103ed087-7843-4c6d-af4a-c965fccc2d1d.MOV

**Comment by rodydavis** [comment]
This has been fixed, but please open a new issue if there are still problems!
