### ISSUE TITLE
Unable to Delete Playlist

### ISSUE THREAD

**Issue by jerickson1075** [hymns-for-worship/issues#16]
When attempting to delete a playlist, the pop-up message asks if I want to discard changes, with the only options to confirm or cancel.  This escapes the delete process without deleting.  

This is observed on macOS, iPadOS, and iOS - with all having the latest GA software. 

The procedure used to delete is by selecting Playlists from the left panel, then opening the playlist, then clicking on the trash can in the upper right.

Thanks in advance for your help!  And no urgency here.  God, Family, and Christmas first. Please don’t worry about this until after the New Year.

**Comment by rodydavis** [comment]
Awesome thanks for the bug! I will do a test and roll out a fix if needed!

**Comment by jerickson1075** [comment]
Thanks Rody!
