### ISSUE TITLE
Sync Across Devices Very Slow

### ISSUE THREAD

**Issue by jerickson1075** [hymns-for-worship/issues#17]
When adding a song to Favorites, the time to sync across devices is very slow.  I do not know the actual time because I’ve been too impatient to wait it out.  However, if I sign out and sign back in, the updates are immediately there. So, I’m assuming this is due to a timer value somewhere. I’d love it if it would push updates.  But, if that’s not feasible, maybe the timer could be shortened instead?

This is observed on macOS, iPadOS, and iOS - with all having the latest GA software. 

Thanks in advance for your help!  And no urgency here.  God, Family, and Christmas first. Please don’t worry about this until after the New Year.

**Comment by rodydavis** [comment]
Thanks for the bug! Right now it is very much offline first. If you visit the screen for the first time it refreshes (or clicking the icon), but I need to test cross device sync. It should be instant.

Now that I'm looking at it I need to add a refresh icon to the playlist details screen!

**Comment by jerickson1075** [comment]
Thanks Rody!!

**Comment by rodydavis** [comment]
Should be fixed on latest for android! For iOS working on rolling out the update

**Comment by jerickson1075** [comment]
Thanks!  I'll stand-by for iOS.

**Comment by rodydavis** [comment]
Testing on beta and it looks like it is fixed now! (But also added multiple ways to refresh)

Will publish the release on the App Store!
