### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by jerickson1075** [hymns-for-worship/issues#18]
One last one…

Favorites doesn’t have a way to sort.  This issue on its own is not really a big deal.  But when you add in the fact that the sort across devices doesn’t line up the same, that’s a little more problematic. So, using Playlists instead is a great alternative. But one issue here: the only sorting I see is drag and drop. For most playlists, this is more than adequate. It’s fantastic!  But when working around Favorites limitations in order to save a complete repertoire, drag and drop becomes a lot more difficult to work with.

This is observed on macOS, iPadOS, and iOS - with all having the latest GA software. 

Thanks in advance for your help!  And no urgency here.  God, Family, and Christmas first. Please don’t worry about this until after the New Year.

**Comment by rodydavis** [comment]
I had a sorting feature for all lists and will work to bring that back (even for playlists). 

I'll comment back here when rolled out!

**Comment by jerickson1075** [comment]
Awesome!!  Thanks so much!

**Comment by rodydavis** [comment]
Recently rethought this, and landed on adding a calendar for playlists! Curious on your feedback. This should make it a lot easier to organize
