### ISSUE TITLE
Cant add to playlists

### ISSUE THREAD

**Issue by Brettcheney** [hymns-for-worship/issues#21]
When I search through hymns on the new mobile update I can't just add them from the song books like I could before. And when I go to the playlist to add songs through that feature, it has songs 1-99 and then jumps to the 1000 which is impractical for me since my church only has songs in the song books and this is how I prepare for song leading.

**Comment by rodydavis** [comment]
Would it be possible to add a screenshot? This is definitely not desired. I also can add back the “add to playlist” button on the hymn screen

**Comment by rodydavis** [comment]
Added back on the latest update!
