### ISSUE TITLE
Can’t sync playlists between devices

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#22]
All of my playlists are now only stored locally. I used to be able to access pkaylists from my phone or my tablet, as long as I was logged in. I can no longer do this since the recent app update. Both devices are using the latest version of iOS.

**Comment by rodydavis** [comment]
There is a problem with migrating the old playlists, but I'm working on moving them hopefully.

The latest should fix the cross device sync

**Comment by vsobris** [comment]
The syncing and playlist edit issues appear to have been resolved. Thank you! In the last major overhaul done to the app, those versions allowed for quickly removing songs with the trash can icon. Is that something you’ll be adding back?

**Comment by rodydavis** [comment]
I moved it to the more drop down! But I am planning on swiping actions like gmail!

**Comment by rodydavis** [comment]
Adding swipe actions to 2.1.18 👀
