### ISSUE TITLE
Update deleted all playlists

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#24]
The most recent update deleted all of my playlists. They were not recovered when I logged into my account. This also happened with the update 5-6 months ago.

**Comment by rodydavis** [comment]
This should not be the case moving forward. If there are a tone of playlists please let me know and I can try to write a migration script. But I switched databases and also combined playlists and presentations so some stuff can’t migrate

**Comment by vsobris** [comment]
They are only for my personal use in services, so it’s not an issue worth causing the extra work of writing a script. Thank you!

**Comment by rodydavis** [comment]
I think I can migrate everyone’s, but with the assumption that some things might not transfer properly.

**Comment by rodydavis** [comment]
Update rolling out **2.1.20** which fixes this!
