### ISSUE TITLE
No option to add song to playlist when viewing song information

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#25]
When viewing a song in the app, I don’t find any option to add the song to a playlist. Previous version of the app allowed for this. The only way to add a song to a playlist in the current app is to go to the playlist, click add, then look up the song.

**Comment by rodydavis** [comment]
Will add that feature back! Wasn’t sure if people were using it. Glad it was useful!

**Comment by vsobris** [comment]
Thank you! It’s nice to have this feature back! It looks great too! Very easy to use.

**Comment by rodydavis** [comment]
Added on the latest update!
