### ISSUE TITLE
Small slideshow exporting bugs

### ISSUE THREAD

**Issue by headmasterditto** [hymns-for-worship/issues#26]
Howdy, liking the new update so far, and just noticed a couple of small bugs when generating our slides for this morning.

1) Hymn # 001 appears to generate three times (three title slides, three verse 1's, etc.) when creating slides. Thus far this hasn't occurred with any other songs, just # 001 for some reason.

2) The feature to edit/remove individual verses from generating doesn't appear to have any effect on the output.

Attached are the playlist settings I used to test this, and the slideshow resulting. Neither issue is critical--both are easy enough to fix by just deleting the slides manually--but I figured they were worth mentioning.
[playlist-result.pptx](https://github.com/hymns-for-worship/issues/files/10369582/playlist-result.pptx)
![playlist-setup](https://user-images.githubusercontent.com/44350163/211220949-ad5625bb-caad-4528-85ec-3a6d4ecd1e05.png)

**Comment by rodydavis** [comment]
Ok thanks for calling this out!

**Comment by rodydavis** [comment]
Should be fixed now! Was a caching issue

**Comment by headmasterditto** [comment]
Issue 1 is resolved nicely, still having issue 2 crop up but in time, I'm sure. Thanks for the work.

**Comment by rodydavis** [comment]
Ok I’ll write some tests to make sure!

**Comment by rodydavis** [comment]
Update rolling out **2.1.20** which fixes this!
