### ISSUE TITLE
Issues searching by title

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#28]
When searching for songs by title, the results do not populate accurately based on a partial entry. For example, search “The Lily of the Valley” by title, and watch the results that populate as you type each letter. Typing “The lil” does not yield the song in the results, but the song will appear as soon as the word “lily” is completed. This makes it difficult to search for songs when you can’t quite remember the name. From the search tab, the ability to search lyrics helps, but there is no ability to search lyrics when using the add button within a playlist.

**Comment by rodydavis** [comment]
More context on the query engine:
https://www.sqlite.org/fts5.html


Supported queries:
```
<phrase>    := string [*]
<phrase>    := <phrase> + <phrase>
<neargroup> := NEAR ( <phrase> <phrase> ... [, N] )
<query>     := [ [-] <colspec> :] [^] <phrase>
<query>     := [ [-] <colspec> :] <neargroup>
<query>     := [ [-] <colspec> :] ( <query> )
<query>     := <query> AND <query>
<query>     := <query> OR <query>
<query>     := <query> NOT <query>
<colspec>   := colname
<colspec>   := { colname1 colname2 ... }
```

**Comment by rodydavis** [comment]
Added fuzzy search on all lists, should help with this case!

**Comment by vsobris** [comment]
The search is now broken. I only receive a “searching” screen that never goes away. I can sometimes search by lyrics, if I disable all other options.
