### ISSUE TITLE
Playlist sorting issues

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#29]
Two issues with sorting playlists. The drag and drop scrolling is very slow (at least on iOS). This wouldn’t be much of an issue until you get a couple dozen songs or so compiled into a playlist. 

The second issue is that the add button within the playlist covers the drag and drop button of the last song in the list (when there are enough songs for the list to span the length of the screen). This is on iOS for iPhone. You must use the icon on the right of the list item to drag and drop, holding down elsewhere on the title does not enable dragging.

**Comment by rodydavis** [comment]
Should be much faster now btw.

For the last item in the list still trying to figure a good ux. Going to see if i can add padding to the list at the bottom!

**Comment by rodydavis** [comment]
Fixed on 2.1.26

**Comment by rodydavis** [comment]
This will roll out to production after the current release (2.1.25) is reviewed and approved
