### ISSUE TITLE
App no longer showing sheet music

### ISSUE THREAD

**Issue by CatherineHebert** [hymns-for-worship/issues#30]
I have been trying to access my sheet music since there was an update done in July of 22.  I am extremely frustrated.  Our congregation doesn't have enough songbooks in print form and that used to not be a problem since I had the digital version.  I have not been able to access the sheet music at all since around July.  Updating Purchases does nothing (well, it says it is completed but it doesn’t work).  I don’t mind using Lyrics, but I find that there are mistakes and/or different lyrics and missing verses in some of the songs so I prefer not to.  Also, if we are singing a song I don’t know, I want the sheet music with notes.

If we can’t fix this, I’m willing to just buy another copy, however when I go to the App Store it only has the OPEN option, not BUY.  I tried deleting my account, but it says I don't have one.  Yet I just 2 minutes before managed to change the password, so obviously I do have an account, plus I used it since March 2020 with sheet music - I remember paying for it.

I may have changed my email address from when I first bought the app and later changed it - but I can't be sure.  I can't seem to log in to either, despite trying to reset password.  Both emails are still active working emails.

At this point, I would just re-purchase, but the App Store doesn't give me the option.  

I hope you can help me.  It's a great app and I enjoyed it when I had it running! P.S. I had to edit to remove my email address, as I did not realize this was a public forum/platform and I don't want any spam.

**Comment by rodydavis** [comment]
Update rolling out **2.1.20** which fixes this

**Comment by CatherineHebert** [comment]
Hi Rody,
Thank you!!

I will keep checking for the update and crossing my fingers!

Regards,
Catherine Hebert

**Comment by CatherineHebert** [comment]
I just downloaded 2.1.21 and nothing has changed for me.  

Catherine

**Comment by rodydavis** [comment]
Ok if I understand correctly there is a possible account mismatch.

for the App Store if you try to repurchase with the same iCloud account it will not charge you twice. Restore should work too.

once a successful purchase / restore happens it saves the purchases to the cloud to be used on other devices.

switching accounts on hymns for worship is fine as long as the iCloud account is the same.

other setups are not covered, am I explaining that ok?

What do you mean the App Store doesn’t give an option to restore?

**Comment by CatherineHebert** [comment]
You’re probably explaining it properly, I’m just not tech savvy.

By iCloud account do you mean my Apple ID that I use for the AppStore?  If so, I’ve only ever had one Apple ID, however I’m not sure when I changed my email address that is connected with my Apple ID, it could be since I first downloaded it in 2020 when it first came out.  It’s just the email that I changed not the Apple ID. 

When I did the update today it didn’t try to charge me - just let me download the update. 

When I open the Hymns for Worship app I can search for a song and the Lyrics will show.  When I try to the Music tab (for sheet music) I get just the following message “Hymnal not found."  

Then I go to Home/Hymnals and get this message “No items found.”

So then I try More… / Settings/ Downloads and I see a grid with dozens of boxes going 3 across and each box has what looks like a trash can in the bottom right corner.  Nothing happens if I click on those trash can icons.


So then I try Settings/ $Products and I can see the Hymns for Worship Revised, Supplement and eChoice.  Under that I click on Restore Purchases.  I get a pop-up “Verification Failed” Your Apple ID or password is incorrect. Cancel or Try Again” - yet when I did the upload it didn’t charge me.
 
Now, here’s the weird part.  When I clicked Cancel I got a pop-up saying App Store in the top left and then a picture of the Hymns for Worship (Revised) in-App Purchase with an email which is my Apple ID email and Price $34.99 and then a blue box saying “Purchase”.   Hmmm.  
*note - On my laptop I can log into my Apple ID account using the email and password I’m asked for on the HFW app - so obviously 

If we can’t fix this I guess I could just follow what I wrote above to get the point where it asks me to purchase again and just buy it all over again. Sigh.  But I’ll see if any of this can get us anywhere first.

Thanks,
Catherine

**Comment by CatherineHebert** [comment]
After I sent my reply just now I was looking on my Apple ID on the web and saw something about 3 of my apps using Sign in with Apple ID so I clicked on that and got this - could this be part of the problem? (I remember setting this up when I was trying to fix the HFW app a few weeks ago).  Should I cancel that? I might have used a different email for Apple ID when I did that - I took that one off today if it was the gmail one as I thought that might be confusing things.

**Comment by rodydavis** [comment]
https://github.com/hymns-for-worship/issues/issues/35#issuecomment-1422089669

**Comment by rodydavis** [comment]
Will be fixed on **2.1.22**.

Found out hymnals had a parse error on launch in addition to the in app purchase bug.

**Comment by CatherineHebert** [comment]
It’s working!  Thank you, thank you, thank you!

**Comment by rodydavis** [comment]
Oh I'm so very happy ❤️

**Comment by CatherineHebert** [comment]
Hi Rody,
I spoke to soon - just have been too busy to update you.

It only worked that one time.  Now I get a little icon when I try to go to sheet music.  It’s a little square box with a zig zag in it.  Looks like a broken link?

Sorry to have be the bearer of bad news again.
Catherine.

**Comment by rodydavis** [comment]
Which song number and which app version are you on?

![image](https://user-images.githubusercontent.com/31253215/224507366-9a7c0ccf-ebfb-4dad-bd93-2698cbcfcb18.jpeg)

**Comment by CatherineHebert** [comment]
Hi Rody,
Ahh - so I see there is yet another update - I still had the one from our last correspondence. 

It’s seems to be working again - thank you.  

Is there a setting in the app that I can have it notify me when a new update is available?

Thanks again,
Catherine

**Comment by rodydavis** [comment]
Nothing at the moment but working on push notifications to help with that!
