### ISSUE TITLE
Hymns for Worship

### ISSUE THREAD

**Issue by Dmark2005** [hymns-for-worship/issues#31]
I purchased the $24.99 subscription in August 2022 but now it won’t load on my iPad. I tried restore purchases but that didn’t work. I clicked purchase and it says I’m already subscribed. How can I get it restored? It was working until my app updated.

Thanks

Mark
littlespider4@icloud.con

**Comment by rodydavis** [comment]
It’s working on iOS but iPadOS seems to have an issue

**Comment by rodydavis** [comment]
Related: https://developer.apple.com/forums/thread/717748

**Comment by rodydavis** [comment]
Update rolling out **2.1.20** which fixes this hopefully, please reopen if still an issue. Switched payment systems and should be resolved
