### ISSUE TITLE
Hymnals purchased but not found on macOS

### ISSUE THREAD

**Issue by 75th** [hymns-for-worship/issues#34]
- 2020 M1 Mac Mini (Macmini9,1)
- macOS Monterey 12.6.2

Both perpetual hymnals purchased:

![Screen Shot 2023-01-29 at 5 38 39 PM](https://user-images.githubusercontent.com/1731790/215362902-b99b9878-86e2-4347-90e1-c9e3933da46d.png)

Yet I can't view the music:

![Screen Shot 2023-01-29 at 5 38 32 PM](https://user-images.githubusercontent.com/1731790/215362923-57c03d2f-a3c0-4a01-b238-8aec99b990c2.png)

I had a ton of blank squares in Downloads at first, and this still happened. I trashed those, then trashed the whole app and redownloaded. Now, after clicking Restore Purchases a few times, I have a single blank square there:

![Screen Shot 2023-01-29 at 5 38 47 PM](https://user-images.githubusercontent.com/1731790/215363000-29dfe46e-d9d7-48fd-83e1-8d4c0791ad04.png)

My hymnals screen is still empty:

![Screen Shot 2023-01-29 at 5 38 32 PM](https://user-images.githubusercontent.com/1731790/215363084-1fb8870a-bdb2-4674-b5d6-688b55257938.png)

**Comment by rodydavis** [comment]
Oh interesting, this is the macos app on M1 macs.. I am going to look into this.

**Comment by rodydavis** [comment]
that did the trick. Build is in beta and will release soon

![415E0410-A9D0-4F41-9319-8DD717D6D406](https://user-images.githubusercontent.com/31253215/216245613-f6df0dc4-05aa-4f91-9068-3c0bd42a0659.png)

**Comment by rodydavis** [comment]
Update rolling out **2.1.20** which fixes this!
