### ISSUE TITLE
“Hymnal not found” for sheet music and slides

### ISSUE THREAD

**Issue by HeyMonroe** [hymns-for-worship/issues#35]
I purchased the Hymns for worship access about a year ago. Recently I found that all of the songs I searched for, gives me an error, “Hymnal not found” when selecting the sheet music or slides. I can see the lyrics. 

Restoring purchases and signing out/in did not resolve the issue. 

There was an update just released, I updated my install and I am still getting the hymnal not found error. In addition, I am now asked to purchase the Hymns for Worship access again. 

Account email : richardboughton@gmail.com

**Comment by rodydavis** [comment]
Thank you for the email:

Currently testing on various devices, but cannot get it to reproduce.

Have you tried reinstalling?

If that works then it is an upgrade problem.

**Comment by HeyMonroe** [comment]
I uninstalled and reinstalled the HFW
app and no longer get the hymnal not found error but it’s prompting me to
purchase the hymnal. I tried to do the restore purchase but it still
prompts me to purchase.

My apple account is under the email address, ***@***.***

My HFW account is under ***@***.***

**Comment by rodydavis** [comment]
Finally was able to reproduce it locally! Working on a fix

**Comment by rodydavis** [comment]
After extensive testing I found the issue. It was not showing up because cloud purchases were loading for me before local ones so I was not being able to test the api properly.

Its all working now for **2.1.22**.

Stay tuned for rollout

**Comment by HeyMonroe** [comment]
That did it!

 

I am no longer getting Hymnal not found and I can now see sheet music and slides on the songs.

 

Thank you for your help with this!

 

-Richard

**Comment by rodydavis** [comment]
You are so welcome! Sorry for the delay, was a very tricky bug, and just needed a solid way to reproduce
