### ISSUE TITLE
Unfavorite a hymn

### ISSUE THREAD

**Issue by acooper221** [hymns-for-worship/issues#36]
Helloooo!
I accidentally favorited a song and now it won't let me unfavorite the song. I'm on Android on a Pixel 6 pro.

Thank you, Andrew Cooper

**Comment by rodydavis** [comment]
I guess it will be loved forever! Haha

No I will check it out. You should be able to remove from the library tab too.

**Comment by acooper221** [comment]
Hahaha!
I tried removing it from there too, but still wouldn't work.
Thank you!

**Comment by rodydavis** [comment]
**2.1.23** is rolling out and fixes this! Please reopen if it is still an issue!
