### ISSUE TITLE
Android user not able to purchase eChoice subscription by itself

### ISSUE THREAD

**Issue by dkladd** [hymns-for-worship/issues#37]
Good evening. I have an android user who is unable to purchase eChoice subscription by itself. He has the option to purchase the Revised version and the Supplement but doesn't give the eChoice. It only shows the features and a "done" button. The icon shows red as well. Thanks!

**Comment by rodydavis** [comment]
Oh got it! I will look into this. 

Can you give an example of which song you are looking at and exact steps to reproduce?

**Comment by dkladd** [comment]
Sure, I'd be happy to. Here is a screen recording of the process that was taken. Let me know if I can provide any additional information to help. Thanks for looking into this!

https://www.vzmessages.com/vl/a1525388d958bca2138d2dcf4e9d20f7e1c33786

**Comment by rodydavis** [comment]
What happens when you click restore by the way?

**Comment by rodydavis** [comment]
There was some incorrect copy on the screen too. It was saying "Done" until the products were loaded. Will be fixed on a future update.

**Comment by rodydavis** [comment]
Tracking here: https://github.com/hymns-for-worship/issues/issues/40
