### ISSUE TITLE
First and Last slides of songs/song sections are empty

### ISSUE THREAD

**Issue by headmasterditto** [hymns-for-worship/issues#38]
Just noticed this in preparation for tonight, but there were several missing slides in the PowerPoint export. It looks (to me, at least) like it might be a caching issue again, or maybe there's something on the server that's been moved, because I actually found the error code this time, albeit kinda hard to read since it's dark on dark.
![AE2840E3-01ED-4D26-BCC0-7BC037C5EA18](https://user-images.githubusercontent.com/44350163/219215611-876d75de-ad2a-457f-b37d-279eb2472114.png)

**Comment by rodydavis** [comment]
**2.1.23** is rolling out and fixing this. There was a library sync issue with presentation creator
