### ISSUE TITLE
Cannot see Music

### ISSUE THREAD

**Issue by GaryTN-VOL** [hymns-for-worship/issues#40]
When I hit the Subscribe or Restore Purchases, it acts like it might work, but  no success.   Hitting Subscribe takes me to a page describing 3  different things - Offline Access, Update, and Sheet Music. Also  says “Done” and also displays further below the “Restore Purchase” link.  I click on it and it indicates success with a message at the bottom that states “Purchase Restored”.   However, I cannot find how no music.  Nothing really has changed with these actions.  Maybe I am doing something wrong.  Apple iPhone 14 Pro w/  iOS 16.3.1.

**Comment by rodydavis** [comment]
What does it say on the hymn details screen for music or slides? Could you paste a screenshot?

**Comment by GaryTN-VOL** [comment]
Shows this same view as in this screenshot.

**Comment by rhcavender** [comment]
I’m having the same issue along with cannot see slides

**Comment by rodydavis** [comment]
The next update will show the correct that. It’s actually loading but I had the wrong text there

**Comment by rodydavis** [comment]
Fixed on 2.1.25

**Comment by rhcavender** [comment]
Why am I not getting the chorus of the songs on the slides?Randy Sent from my iPhoneOn Mar 4, 2023, at 10:53 PM, Rody Davis ***@***.***> wrote:﻿
Closed #40 as completed.

**Comment by rodydavis** [comment]
Android rolled out, iOS update is still in review!
