### ISSUE TITLE
Images fixed, choruses not loading

### ISSUE THREAD

**Issue by headmasterditto** [hymns-for-worship/issues#42]
The update just now has definitely fixed the image loading issue, so thank you for that, the app itself is much smoother now. However, both the internal view and exported slides have no chorus sections. Attached screenshot with tested settings and output result.
[New Playlist.pptx](https://github.com/hymns-for-worship/issues/files/10799359/New.Playlist.pptx)
![IMG_0206](https://user-images.githubusercontent.com/44350163/220502339-a20fa7c6-639d-4fd3-a294-3f1cce018262.png)

**Comment by rodydavis** [comment]
Will look into the backing image database. Could be named wrong. 

Was able to reproduce on my end!

**Comment by rodydavis** [comment]
Issue found (minor typo), and will be resolved on the next update!

**Comment by headmasterditto** [comment]
Cool. Thanks for all that you do.

**Comment by rodydavis** [comment]
Of course!

**Comment by rodydavis** [comment]
Fixed on 2.1.25
