### ISSUE TITLE
eChoice Hymnal unavailable

### ISSUE THREAD

**Issue by Frank4254** [hymns-for-worship/issues#43]
I can purchase both the revised and supplement hymnals, but I cannot purchase or subscribe to the eChoice. Whenever I press it I get sent to a screen giving the options "done" or "reactive purchase", neither of which do anything. I am sent to the screen whether I go through settings and products, or by finding a hymn and going through it. I am on Apple

**Comment by rodydavis** [comment]
Latest update rolling out should fix this!

**Comment by rodydavis** [comment]
Tracking here: https://github.com/hymns-for-worship/issues/issues/40
