### ISSUE TITLE
Search is broken 

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#47]
Searching for hymns by anything except lyrics usualk6 leads to a “searching” screen that never goes away. This began after update last weekend. Sometimes I can populate results by disabling all criteria except lyrics, but not always.

**Comment by rodydavis** [comment]
I have noticed this a few times where if you start searching too quickly before the index is built it loads and never resolved.

I have verified this back going back to the previous screen and then back to search which will then work as expected.

To help with this, I added back search to all lists to help with fuzzy searching and leaving the global search with the full text search support.

**Comment by vsobris** [comment]
Attached is what I’m experiencing.

**Comment by vsobris** [comment]
Maybe not. I can’t attach the recording here. I can email it if you want, tell me where.

**Comment by rodydavis** [comment]
You can upload screenshots and small videos by dragging them to the input field!

If we keep the discussion here it can help others.

**Comment by vsobris** [comment]
https://user-images.githubusercontent.com/121978497/226207670-165aeed3-18a2-4556-b51d-24db091d2ad7.MOV


I can’t fit it into a clip here, but at the end the ”searching” screen was up for a few seconds before I delete the entry. Note that these results will not populate even if I leave the screen idle for 30 seconds.

**Comment by vsobris** [comment]
https://user-images.githubusercontent.com/121978497/226207873-65a6ecba-8672-4d3a-a846-6cdbb304103a.MOV



Part 2

**Comment by vsobris** [comment]
Example of the results never populating when the “Searching…” prompt is visible.

https://user-images.githubusercontent.com/121978497/226208005-df9d377d-def0-4767-8331-4892c9e6a9ce.MOV

**Comment by vsobris** [comment]
After deleting characters, results alternate between not found and more stalking without populating a list.


https://user-images.githubusercontent.com/121978497/226208446-ef076666-22f7-4bc4-91b0-a5db0a6d886d.MOV

**Comment by rodydavis** [comment]
Thanks for the uploads! Definitely working on this, and will be fixed on the next version.

The database uses a virtual table and is never returning on some joins

**Comment by rodydavis** [comment]
Will be fixed on 2.2.3

**Comment by rodydavis** [comment]
Fixed on 2.2.4
