### ISSUE TITLE
Scroll speed on iOS still very slow

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#48]
The scroll speed for reorganizing songs in playlists on iOS has not increased. I think you mentioned this was fixed, but I can’t find the closer issue where I mentioned this.

**Comment by vsobris** [comment]
Also on iPadOS

**Comment by rodydavis** [comment]
It is improved for the sync time on fast internet but it's a case of an optimistic update that for a split second it's ahead of the server, gets a update before the server responds and then the final truth back from the server.

Working on improving this though further with a polling technique

**Comment by rodydavis** [comment]
Update 2.2.2 just rolled out last night and fixes this!
