### ISSUE TITLE
Issues with “My Library” after recent update

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#49]
After the recent update where you added tabs under “My Library”, my playlists do not show up under the “playlists” tab. My playlists do show up on the Home Screen, but not anywhere under My Library.

I also can’t delete stakeholders from my list after adding.

**Comment by rodydavis** [comment]
Ok so if you click on the search icon if you click on playlists it will show all the playlists (even ones without a date). 

If there are playlists that are not date specific you can put them on the starred playlist page now too.

I should have communicated the change better, it's now optimizing for a calendar view where a playlist is for a specific day.

In the future you could imagine seeing a shared calendar for a church or group and see other people's playlists for a given day.

**Comment by vsobris** [comment]
Do you mean that this will be updated in the future? Currently I do not see any option to search or favorite playlists. 
![EA5B2F56-F493-475A-86BE-23595CCD61A9](https://user-images.githubusercontent.com/121978497/226172126-cb90ebbe-70a4-411d-a9cf-1e9ef25d2350.png)
![2EDCDD84-8B83-4D3A-A3A9-F5F9EFB32B8D](https://user-images.githubusercontent.com/121978497/226172128-8719a715-31f0-481a-a64c-0e46b5eef64f.png)
![2B011706-1EE5-47CA-971B-F7DF18338C22](https://user-images.githubusercontent.com/121978497/226172130-0e473a3f-6cb4-4f8b-80dc-d281991c2ade.png)
![819B4ECA-58A0-43E4-9EFA-B1728EE44665](https://user-images.githubusercontent.com/121978497/226172133-79b51e4b-e530-4fcb-98e8-6abbcb036b2c.png)
![173FC147-01AB-4436-9119-84172D6C9778](https://user-images.githubusercontent.com/121978497/226172134-2a16aad7-5f74-4d6b-b8be-83ae03d7ba88.png)

**Comment by rodydavis** [comment]
Yes it will be updated. 

And that grey screen is what I needed to see. Looks like something is not rendering and will look at the logs.

It should be showing a calendar there.

**Comment by rodydavis** [comment]
I was also meaning going to `menu > my playlists`

**Comment by vsobris** [comment]
In addition to being unable to delete shareholders, I am also unable to delete topics.

**Comment by rodydavis** [comment]
Update 2.2.2 just rolled out last night and fixes this!
