### ISSUE TITLE
iPadOS crashes sometimes when viewing slides

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#50]
App crashed a couple times when viewing slides on my iPad and scrolling at the pace of singing. I don’t usually use slides on my phone, so not sure about iOS.

**Comment by rodydavis** [comment]
Oh that's not good! Is this on hymn details? And also is it in full screen mode where it hides the other parts of the UI in the app?

**Comment by vsobris** [comment]
It is under the slides tab of the hymn and in full screen mode. If it helps, I was using the “smart invert colors” accessibility feature on my iPad as well. I use this due to visual impairment.

**Comment by rodydavis** [comment]
Thanks for letting me know about smart invert. Will add that to my testing

**Comment by rodydavis** [comment]
Is this still happening? Please test on **2.2.5**
