### ISSUE TITLE
Error message throw when attempting to "Sign in with Google" on Samsung Tab A8 (2019)

### ISSUE THREAD

**Issue by justinmccuistion** [hymns-for-worship/issues#51]
As a user, when I am using the Hymns for Worship app from the Google Play store on a Samsung Tab A8 (2019) and I try and log in, I get an error message and am not logged in.  The expected result is that I would be logged in an able to access my purchased library.

# Steps to reproduce:
1.  Launch app
1. Click the profile icon in the upper right ("Edit profile") is displayed.
1. Click the "Sign in" button
1. Choose "Sign in with Google"
1. At the Google prompt which says "Choose an account to continue to Hymns for Worship", I choose the account under which I purchased HFWR
1. There is what appears to be a brief processing and then "An unknown error occurred" is displayed in red font below the "Sign in with Google" button.

**Comment by justinmccuistion** [comment]
![Screenshot_20230319-220416](https://user-images.githubusercontent.com/75227432/226251946-dbca1616-cd8a-49a4-be14-a6a92e2395eb.jpg)

**Comment by rodydavis** [comment]
So that button is to link your current account with google sign in. If you want to sign in with google log out then click the sign in with google button!

This screen comes directly from the authentication provider and seems to have this bug. I'll raise it with them.

**Comment by justinmccuistion** [comment]
Hi Rody - the challenge here is that I can not log out as I have not been able to log in.  When I navigate to the profile area all I see is a message that says "Please sign in to use this feature" with a "Sign in" button.  You are probably right that it is the auth provider throwing the error, but perhaps the integration configuration is the source of the issue?  Does the current integration support MFA which is turned on with my Google Account?

**Comment by rodydavis** [comment]
It should work with MFA. It's working on iOS and web and may be something with the android google client login.

I'll do testing and try to push out a patch soon

**Comment by justinmccuistion** [comment]
I completely removed the Google account in Android device Settings and went through the process to log in again - same error.  Let me know how I can assist, but I don't have the tools to debug Android.

**Comment by rodydavis** [comment]
Can you send me an email with your account info? I will check your account locally.

rody.davis.jr@gmail.com 

I will test on my pixel and Samsung!

**Comment by rodydavis** [comment]
For others facing it:

In the meantime use email login with the same email address and the account will be linked

**Comment by rodydavis** [comment]
Update 2.2.2 just rolled out last night and fixes this!

**Comment by justinmccuistion** [comment]
The Google Play Store only shows version 2.2.1 as the current version available and the app shows 2.2.1+613 as the installed version on my Tab A.

**Comment by rodydavis** [comment]
Still rolling out! Just pushed late last night, usually takes about a day or two
