### ISSUE TITLE
Playlists Broken

### ISSUE THREAD

**Issue by jerickson1075** [hymns-for-worship/issues#54]
Hi there.  Playlists are broken.  On my MacBook Pro, I can see the songs in the playlist that I last added.  However, I cannot delete songs.  On my iPad Pro and iPhone 14, my playlists are completely empty.  I cannot add songs to either.  Please note that I did not delete the songs.  It should have the same songs as my Mac does.  And lastly, the Playlist landing page is blank on iPad and iPhone.

**Comment by rodydavis** [comment]
Update 2.2.2 just rolled out last night and fixes this!

**Comment by jerickson1075** [comment]
Thank you so much!!
