### ISSUE TITLE
Cannot screenshot a playlist 

### ISSUE THREAD

**Issue by ajamerson67** [hymns-for-worship/issues#56]
I’m unable to take a screenshot to send to deacon to create presentation

**Comment by rodydavis** [comment]
There are multiple options to export a playlist to send.

I would highest the markdown which sends the names.

What is the app doing when you screenshot?

**Comment by rodydavis** [comment]
Images can no longer be in a screenshot though.

**Comment by rodydavis** [comment]
I did find the bug and will work on fixing it, but images will still be blocked

**Comment by ajamerson67** [comment]
Working now. Thanks!
