### ISSUE TITLE
Discord link is expired or invalid 

### ISSUE THREAD

**Issue by ElijahSink** [hymns-for-worship/issues#59]
Both the in-app link and the one in the README do not appear to work. Opening it in the browser gives an error message: "This invite link is invalid or has expired"

**Comment by rodydavis** [comment]
For the beta?

**Comment by ElijahSink** [comment]
No, the invitation to the discord server which is in the README and the one that you can find in the app settings.

**Comment by rodydavis** [comment]
Does this link work?

https://discord.gg/UbWTzqxd

**Comment by ElijahSink** [comment]
Yep! 👍
