### ISSUE TITLE
PowerPoint export not working 

### ISSUE THREAD

**Issue by HitmanXL** [hymns-for-worship/issues#60]
I am using 2.2.8 for iPhone. I trying to export a playlist to PowerPoint. Every method I have tried to export the to has said the file is corrupt.

**Comment by rodydavis** [comment]
Can you screenshot the playlist details so I can see what's in it? Or share the link or markdown

**Comment by HitmanXL** [comment]
![IMG_1333](https://github.com/hymns-for-worship/issues/assets/134805871/76a42196-18b6-4800-b077-50ccddf4cb78)

**Comment by HitmanXL** [comment]
No matter what I put in the playlist, or what playlist, or whatever playlist I create I get the same error.

**Comment by rodydavis** [comment]
Working on it! I believed it is resolved in **2.2.9**, but double checking

**Comment by rodydavis** [comment]
Working on this, should be fixed in the next version

**Comment by joescarborough** [comment]
PowerPoint export crashes the app on tablet android 2.2.9...

**Comment by rodydavis** [comment]
It might be the image gallery causing it, but in testing of the new version I haven’t gotten it to test on 4 android phones

**Comment by rodydavis** [comment]
Fixed on 2.2.10!
