### ISSUE TITLE
Purchased Items

### ISSUE THREAD

**Issue by acooper221** [hymns-for-worship/issues#61]
Hello,
I'm having issues with my purchased items, it's not letting me see my purchased items. I've hit restore purchase but its not working.
Thank you.

**Comment by acooper221** [comment]
Looking into things further, non of my playlist are showing either.

**Comment by NeoShader** [comment]
Same here. Tried reinstall and relogin. Android 2.2.g+684

**Comment by rodydavis** [comment]
Fixed on 2.3.0!
