### ISSUE TITLE
Sort by number

### ISSUE THREAD

**Issue by hathcode** [hymns-for-worship/issues#62]
Small nitpick: When viewing the song list for a hymnal, and sorting by `number`, the list is sorted weird (eg: order is 1, 10, 100, 101, 102, etc rather than 1,2,3,4,5 etc).  Maybe it's doing an alpha sort on the numbers?
I'd be glad to take a look and attempt a fix 🙂

**Comment by rodydavis** [comment]
Fixed on the next version I am rolling out soon!

**Comment by rodydavis** [comment]
Fixed on 2.2.10!
