### ISSUE TITLE
Song 28 Returns "no image" on mobile

### ISSUE THREAD

**Issue by hathcode** [hymns-for-worship/issues#63]
After purchasing hymnal, other songs load music and slides. After multiple tries (and verifying connection), music and slides show "No Image"  for #28

![Screenshot_20230719-201216](https://github.com/hymns-for-worship/issues/assets/19431253/d161247e-215e-4d7a-ac35-3ac7b5a4b9c1)

**Comment by rodydavis** [comment]
Thanks! Will be fixed on the next update.

**Comment by rodydavis** [comment]
Fixed on 1.1.0 which i am rolling out!

**Comment by rodydavis** [comment]
Fixed on 2.2.10!
