### ISSUE TITLE
App Crashes on every song

### ISSUE THREAD

**Issue by ScottHale325** [hymns-for-worship/issues#64]
My app keeps crashing with every song. I am using iPhone 12 and iOS 16.1.1. App version is 2.2.8+680. Not able to use the app at all currently. I tried offloading and also deleting the app and reinstalling but still continues to crash. Please help. Thanks!

**Comment by rodydavis** [comment]
Fixed on 2.1.10 which i am working on rolling out!

**Comment by ScottHale325** [comment]
![CF168386-A3A9-4001-A899-23E81B2DA5D5](https://github.com/hymns-for-worship/issues/assets/141388972/bf08fb18-f806-4669-bd4d-226903116b0f)

I am now not able to restore my purchase. If I select restore, it just spins. If I select purchase, it throws the error in the attached picture. Please help!

**Comment by rodydavis** [comment]
Looking into it!

**Comment by rodydavis** [comment]
Found the bug and will be fixed on the next release!

**Comment by rodydavis** [comment]
Fixed on 2.2.10 and 2.3.0!
