### ISSUE TITLE
Powerpoint Export - No offsets in background image

### ISSUE THREAD

**Issue by brianhudd** [hymns-for-worship/issues#7]
The export to PowerPoint is exactly what I was looking for.  I noticed that the entire image streches across the entire slide and I have to go through and adjust to create a margin by going to format background and adding 1% to Offset left, right, top, and bottom.  I don't know if this could be added via code or a setting to allow a border in export.  Unfortunately, highlighting all and changing the offset ends up applying the same image to all slides and they have to be done one by one.
Thanks for the updates, this is great!

**Comment by rodydavis** [comment]
Im working on a image update on how the images are stored on the server. still in progress, but im working on the padding fix.

I am converting the PDFs to PNGs on the fly and need to check for trim

**Comment by rodydavis** [comment]
This has been fixed, but please open a new issue if there are still problems!

**Comment by brianhudd** [comment]
Rody,
Thanks for all the fixes and enhancements.  Everything looks great!

-Brian
