### ISSUE TITLE
Purchases

### ISSUE THREAD

**Issue by acooper221** [hymns-for-worship/issues#71]
My purchases are not being restored

**Comment by rodydavis** [comment]
Looking into it!

**Comment by rodydavis** [comment]
iOS or Android?

**Comment by acooper221** [comment]
Android 14 public beta 5

**Comment by joescarborough** [comment]
After update my purchases are not restored. 
It gave error msg when I tried to create a new account
It does say I already purchased HFWR and HfWS but it does not give me access to them. 
It wants me to repurchase eChoice.

**Comment by rodydavis** [comment]
Working on an update for it!

**Comment by rodydavis** [comment]
Should be fixed now!
