### ISSUE TITLE
No share icon for exporting PPT/Excel

### ISSUE THREAD

**Issue by rdhclsearch** [hymns-for-worship/issues#73]
The share icon on the iPhone app is missing

**Comment by rodydavis** [comment]
Do you have a plan?

The PowerPoint was under beta access for accounts that purchased both hymnals.

Now it is on the pro plan and basic plan gives view access to sheet music

**Comment by rdhclsearch** [comment]
Rody, I purchased both HFW hymnals and purchased an eChoice subscription / annual pass. 

Also thought I saw in an email that the RJS team members were going to have full access?

-Rhett

**Comment by rodydavis** [comment]
Feel free to email me offline and I will get you access!

**Comment by rdhclsearch** [comment]
Hi Rody,

I checked the app again and still do not see any way to export / share hymn slides.



Rhett Daniel
HCL Software – Commerce, Advisory Services
***@***.***
+1-256-392-9322
________________________________

**Comment by rodydavis** [comment]
Can you send a screenshot of what you mean? The slides can only be exported to pptx

**Comment by rdhclsearch** [comment]
Sure - how?  Believe you have blanked out screenshotting on the app.

Edit:  I remembered my son told me if you screenshot quickly twice it captures - here you go.  No share / export to PPT icon that I can find:

![image](https://github.com/hymns-for-worship/issues/assets/99753021/51d039a6-8fe1-41eb-91c3-1a500c7c530b)
