### ISSUE TITLE
Default to playlist list view vs calendar view

### ISSUE THREAD

**Issue by rdhclsearch** [hymns-for-worship/issues#74]
Playlists default to a calendar view that is not very useful - need the list view to view playlists and the playlists need to be shareable - for instance: song leader shares playlist with soundbooth staff that builds the song worship presentations.

**Comment by rodydavis** [comment]
That's a great point! If you hit playlist search on the playlist screen it will show a list

**Comment by rodydavis** [comment]
Still working on this, getting the presentation creator release ready for the app.

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
