### ISSUE TITLE
Developer Hasn't Acknowledged Purchase

### ISSUE THREAD

**Issue by dkladd** [hymns-for-worship/issues#75]
When purchasing the subscription on an android device this message pops up. Is there anything that needs to be done on the user end?

![image](https://github.com/hymns-for-worship/issues/assets/110351364/2041aad1-4d61-44b2-bf38-8b6412275a06)

**Comment by rodydavis** [comment]
Working on it, using the correct APIs but it is not working for some users. I have an update I am releasing soon

**Comment by rodydavis** [comment]
This should be fixed on the latest android update!
