### ISSUE TITLE
Pro Plan Subscription Issue iOS

### ISSUE THREAD

**Issue by dkladd** [hymns-for-worship/issues#76]
Not sure if this is the right place to post this but I figure it wouldn't hurt. I posted it in Discord as well. Thanks in advance!

I’m using an iPhone and was subscribed to the annual plan prior to the recent conversion. My subscription converted to the basic but when I tried to upgrade to the pro plan it won’t allow me to until my original subscription expires. Since I originally did an annual  subscription it won’t expire until 2024. Is there a way to fix that so I can purchase the pro plan and access it now? I used the export to PowerPoint feature a lot before the conversion and would really like to continue using it before 2024. Thanks!

**Comment by rodydavis** [comment]
Can you try now? I adjusted some backend settings. It should allow upgrade/downgrade at will.

Please let me know if it is not working

**Comment by rodydavis** [comment]
Please test again! There was an issue that is resolved

**Comment by dkladd** [comment]
Thanks for the update! This is what it shows now when I try. I might be doing it wrong though so if there is a different way to try it please let me know. Thanks!![image](https://github.com/hymns-for-worship/issues/assets/110351364/efd18169-2cea-4d77-b8f9-138412b99a04)

**Comment by rodydavis** [comment]
You can also change the plan from the settings right there by choosing a different one under "see all plans". Then just restore in the app and restart if you have issues

**Comment by rodydavis** [comment]
Also tried to fix something on the Apple console and should be fixed now.

It was having the basic plan be prioritized over the pro plan

**Comment by MitchellH79** [comment]
The app just updated. Everything seems to be working great except that i cannot export to PPT.  In the app it shows I have the “Basic” subscription, however when i go to the App Store and look under subscriptions it confirms I have the Annual “Pro” subscription.  Screenshots of both below.
![IMG_0495](https://github.com/hymns-for-worship/issues/assets/156945904/41fe6be6-8939-47a0-bb6c-de2e863dd18a)
![IMG_0494](https://github.com/hymns-for-worship/issues/assets/156945904/e0d427f6-ebbd-484b-974e-acfdcbaddd30)

**Comment by rodydavis** [comment]
What happens when you click restore purchases? It might be loading in a previous subscription from the cloud

**Comment by rodydavis** [comment]
The other thing you can do (which I just verified) is go to the plans and subscribe to pro.

It will say you already own it and not charge twice

**Comment by rodydavis** [comment]
![image](https://github.com/hymns-for-worship/issues/assets/31253215/0dee98c5-fef2-491d-8e60-65c0511f2cce)

**Comment by MitchellH79** [comment]
It says “Restoring” with the spinning circle next to it but it remains with the Basic planThanks,Mitch214-679-0351 On Jan 17, 2024, at 12:07 PM, Rody Davis ***@***.***> wrote:﻿
What happens when you click restore purchases? It might be loading in a previous subscription from the cloud

**Comment by MitchellH79** [comment]
This is the view I get when going to view the plans.  It does not give me an option to subscribe to the Pro plan. It is highlighted as you can see, but no option to select/subscribe to it.Thanks,Mitch214-679-0351 On Jan 17, 2024, at 12:09 PM, Rody Davis ***@***.***> wrote:﻿
The other thing you can do (which I just verified) is go to the plans and subscribe to pro.
It will say you already own it and not charge twice

**Comment by headmasterditto** [comment]
Don't know if this will help at all, but have you tried exporting any slides? When I log in to the web app, it _reports_ that I have the basic plan, but I still have access to the subscription features.

**Comment by MitchellH79** [comment]
The app on my Mac will not let me export.  The option is greyed out.  But on my ipad it is letting me export. Thanks,Mitch214-679-0351 On Jan 17, 2024, at 12:45 PM, headmasterditto ***@***.***> wrote:﻿
Don't know if this will help at all, but have you tried exporting any slides? When I log in to the web app, it reports that I have the basic plan, but I still have access to the subscription features.

**Comment by rodydavis** [comment]
> Don't know if this will help at all, but have you tried exporting any slides? When I log in to the web app, it _reports_ that I have the basic plan, but I still have access to the subscription features. 

There is Free, Basic and Pro.

But sometimes right after logging in it needs to check purchases and sync them. But should but relatively quick

**Comment by rodydavis** [comment]
Also in pricing mine is showing pro, but the settings page is saying basic. That label may be wrong, might be a bug.

Pricing should be correct though

**Comment by alanmsings** [comment]
I’m experiencing the same issue. Clicking restore purchases is unsuccessful.

**Comment by rodydavis** [comment]
Looking into it!

**Comment by MitchellH79** [comment]
I have closed out of the mac chrome app & reopened it several times, logged out from Apple (from within the app), re-logged in with Apple,  but still no change.  It still shows to be the basic subscription.  It will not let me export on the chrome app running on my Mac.On a side note, do yall plan to add to the slides the “End of Verse” and “End of Song” notes in the bottom right hand corner?  That is very helpful IMO & I have to manually add them in whenever exporting from the new HFW app. Thats one thing i really love about the Presentation Creator software..Thanks,Mitch214-679-0351 On Jan 17, 2024, at 1:56 PM, Rody Davis ***@***.***> wrote:﻿
Also in pricing mine is showing pro, but the settings page is saying basic. That label may be wrong, might be a bug.
Pricing should be correct though

**Comment by rodydavis** [comment]
The slide export now does include the "end of verse 1", etc! You can even change the template in settings!

Also open on iOS or android and show me which plan it is on pricing

**Comment by MitchellH79** [comment]
Here is what it shows on my iPhone.  ipad shows the same (i sent those pictures earlier). Thanks,Mitch Himes214-679-0351 On Jan 17, 2024, at 3:31 PM, Rody Davis ***@***.***> wrote:﻿
The slide export now does include the "end of verse 1", etc! You can even change the template in settings!
Also open on iOS or android and show me which plan it is on pricing

**Comment by rodydavis** [comment]
You will have to attach them on GitHub no images came through

**Comment by MitchellH79** [comment]
Just to give you some additional feedback… I exported 3 songs. 2 of them in one playlist & the other by itself.  In the file with 2 songs one of them had all the “end of verse” & “end of song” listed out correctly, but the other said “end of verse 4” on the very last slide.  The song is We Will Glorify The King Of Kings - #141. Both ppt files still giving the error when opening stating that there is a problem with the content & that PowerPoint can attempt to repair.On Jan 17, 2024, at 3:31 PM, Rody Davis ***@***.***> wrote:﻿
The slide export now does include the "end of verse 1", etc! You can even change the template in settings!
Also open on iOS or android and show me which plan it is on pricing

**Comment by MitchellH79** [comment]
Here are those screenshots:
![IMG_0496](https://github.com/hymns-for-worship/issues/assets/156945904/5948466c-b426-4434-a606-7f87abc45f43)
![IMG_0495](https://github.com/hymns-for-worship/issues/assets/156945904/b2fcb56e-030b-49bd-be54-d4a925fdd542)
![IMG_0494](https://github.com/hymns-for-worship/issues/assets/156945904/31f55146-c735-4d35-9b99-a43a0d683675)
![IMG_2602](https://github.com/hymns-for-worship/issues/assets/156945904/16dfbe61-ca37-454b-bcae-933da746c825)
![IMG_2603](https://github.com/hymns-for-worship/issues/assets/156945904/b9135d50-9e75-4a69-a39e-17f0d1b28f70)
![IMG_2604](https://github.com/hymns-for-worship/issues/assets/156945904/7a252c3b-b999-4fbb-9481-0ee8854d4012)

**Comment by rodydavis** [comment]
I am rolling out an update for the account status. 

But you are on the pro plan and should be able to export

**Comment by rodydavis** [comment]
Fixed on version 4.0.0
