### ISSUE TITLE
Cut Off On PowerPoint Export

### ISSUE THREAD

**Issue by dkladd** [hymns-for-worship/issues#77]
I've noticed on several slides where the bottom clef notes are cut off on the most recent PowerPoint exports. It's more prominent on songs that have lower bass notes. The slides in the app don't cut it off so I'm sure it has something to do with the export. Can this be fixed? Thanks! ![image](https://github.com/hymns-for-worship/issues/assets/110351364/6e6d7e5d-67e8-414f-8f1e-86c3bf9bfbb0)

**Comment by rodydavis** [comment]
Thanks for raising this! I will check to see if it is the source image or the copyright that is stamped!

**Comment by rodydavis** [comment]
Working on this for the next update

**Comment by dkladd** [comment]
Thanks for the update! I really appreciate you addressing this.

**Comment by rodydavis** [comment]
This is being worked on and should be fixed in a future update.

Also working on adding the animations from presentation creator and the footer text like "end of verse 1"
