### ISSUE TITLE
Still unable to create account in order to regain purchases and data

### ISSUE THREAD

**Issue by vsobris** [hymns-for-worship/issues#79]
Same issue as described in my previous ticket. Updates in emails. I’m posting it here again because there has been no response, but the issues persist.

**Comment by rodydavis** [comment]
Can you paste some more info here?

What steps did you do to create an account?

If the account had purchases made before august 2023 then there was a bug fix that solved a issue that allowed for lots of users to have access to the purchases without having a completed purchase.

If it is truly purchased the restore for iOS and android will work and other users have verified the restore is working too.

**Comment by vsobris** [comment]
Yes, they were real purchases. I’ve purchased everything but the eSupplement. I think that was three purchases, based on the app layout in 2021. I’m not sure what information you want. I created my account via email originally, but I can’t log in via email as I’ve already shown you. I verified my account using the apple option, but I can’t restore anything. I’ve attached the error message.

**Comment by rodydavis** [comment]
For the email you need to create an account with the same email and a new password.

Accounts created before August need to be recreated, and the data should migrate after.

For the purchases eChoice subscription is replaced by the basic plan. But revised should restore

**Comment by vsobris** [comment]
Previously I was recieving errors creating my account again by email, and then logging in-changing password. I just tried to log in again and it worked. Restoring purchases worked. It shows my plan as “Free” but as far as I can tell I still have access to the sheet music that I purchased before.

Is there a way to make it so the text of the lyrics under a song’s “Details” tab can be as big as it was able to get in previous versions of the app? This is the only drawback for me using the newest design of the app. I struggle to read the lyrics text because the max text size is much lower than it used to be. That plus I’ve lost all of my saved playlist data again, but I can recreate those over time. I read from the lyrics page while singing and study the sheet music to learn the songs, since I am unable to sight read sheet music fast enough due to low vision. I understand I am just a single user and it might not be worth making changes for an uncommon need, but I figured I would ask.

Thank you,

Vince Sobris

**Comment by rodydavis** [comment]
You can easily change the text size of the lyrics!

![IMG_3926](https://github.com/hymns-for-worship/issues/assets/31253215/91180995-062f-4245-a121-a4bff20830a9)

**Comment by rodydavis** [comment]
Are you asking for the absolute max to be increased? Happy to do so 👍🏼

**Comment by vsobris** [comment]
Yes, the max infreased. I don’t know what the max was on previous versions, but the current version has a max that is less than the size I used to use. Thank you!!! I appreciate it.

**Comment by rodydavis** [comment]
Sounds good, happy to do so!

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon

**Comment by vsobris** [comment]
Thank you! I really appreciate it!
