### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by dkladd** [hymns-for-worship/issues#8]
Thank you for including the PDF export function to the app. When I try to export to PDF I get the attached file. I'm not sure what's happening but it exports it into unreadable characters. I've tried this on the web version from both a MAC and PC with the same result. When I try to do it on iOS it just loads but never exports. Could be something I'm doing wrong though. Thanks again for adding this incredibly helpful feature!

[Test-2.pdf](https://github.com/hymns-for-worship/issues/files/9229512/Test-2.pdf)

**Comment by rodydavis** [comment]
Oh interesting! Thank you for sharing this. I will dive into it

**Comment by rodydavis** [comment]
This has been fixed, but please open a new issue if there are still problems!
