### ISSUE TITLE
Slides not properly advancing / missing slides on HFWR #387 (Far and Near).  Also, slides drag all over screen(need to be static/ fixed in place) on iOS.

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#80]

**Comment by rodydavis** [comment]
- Slides not properly advancing
- missing slides on HFWR #387 (Far and Near)
- slides drag all over screen(need to be static/ fixed in place) on iOS

**Comment by rodydavis** [comment]
> * Slides not properly advancing

What is wrong about them advancing?

> * missing slides on HFWR #387 (Far and Near)

Which slides are missing?

> * slides drag all over screen(need to be static/ fixed in place) on iOS

This is meant to allow for pinch to zoom. It used to swipe between but users wanted the zoom. I will consider supporting both, but they are competing gestures

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
