### ISSUE TITLE
Auth Issues on Safari MacOS 14

### ISSUE THREAD

**Issue by thetechguyseth** [hymns-for-worship/issues#81]
Auth flow for creating a new account via OAuth (Google and Apple) didn't work in Safari on MacOS 14. It opened in a new tab and after authentication the redirect retuned an Error 400 object with a blank payload. Normal email sign in did work, but there were a a few UX issues. (Like no confirmation/ auto redirect to sign in on successful account creation) I did not try any other browsers, but I am open to testing with you if you would like.

Judging by some of the conversation on the discord the webapp may still need some love, let me know what I can do to help!

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
