### ISSUE TITLE
Screen Mirror black upon projection

### ISSUE THREAD

**Issue by brbillin** [hymns-for-worship/issues#82]
Upon full screen projection screen mirror via projector turns black. Phone shows image but not projection. Edges of phone screen can be seen but the music area is blacked out. Using Apple 13 phone.

**Comment by rodydavis** [comment]
Probably due to the screenshot api preventing it. Working on the desktop multi window support of internal viewer

**Comment by rodydavis** [comment]
This is because of the no screenshot api
