### ISSUE TITLE
Search bar ignores input on  Library page

### ISSUE THREAD

**Issue by joescarborough** [hymns-for-worship/issues#84]
On my tablet,, When I search using the 2nd search bar it does not accept entry then it blinks and resets. The one on my phone works great. 

I hope this screen shot goes through. 

![Screenshot_20231113-121809~2](https://github.com/hymns-for-worship/issues/assets/31560618/c47b98cf-a8f2-48e3-b1c7-b917f7afef79)

**Comment by joescarborough** [comment]
The search bar circled in yellow above does not work. 
The top search works fine.

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
