### ISSUE TITLE
slides drag all over screen 

### ISSUE THREAD

**Issue by joescarborough** [hymns-for-worship/issues#85]
slides drag all over screen 
This was working well in a previous revision. I could flip to next page easily.
Now I can flip the song out of sight or accidentally mega zoom or create a little tiny hymn sheet which is useful but I would prefer to have the option to have the sheet music full screen and be able to flipnto next slide or sheet.

**Comment by rodydavis** [comment]
There was feedback to switch it to this behavior from the previous version and zoom.

I am going to work to make it a configuration setting

**Comment by rodydavis** [comment]
Will be fixed on v3 that will roll out soon!

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
