### ISSUE TITLE
Loads double pages when accessing song sheets or slides on first time to load

### ISSUE THREAD

**Issue by joescarborough** [hymns-for-worship/issues#86]
When I tap Music, the song sheets load but double pages and the blue dots at bottom of the screen are doubled. When I advance page using the arrow button I get 1 page 1s and 2page 2s
The same happens withte slides. 
But when I go back to the Music tab its okay with proper pages and blue dots 
Thus going back the the slides they are now working as expected. 
This only happens on the first t I me the song sheets or slides load. After that it seems okay.

**Comment by rodydavis** [comment]
Fixed on version 3 where it downloads hymn bundle instead of streaming in the images

**Comment by rodydavis** [comment]
V3 will be rolled out soon

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
