### ISSUE TITLE
PPT Export Never Completes - Just Spins

### ISSUE THREAD

**Issue by kastenk** [hymns-for-worship/issues#87]
I’ve tried on 3 different Apple devices, using all different web browsers, and have been unsuccessful in getting my playlist to export to PowerPoint.  It just spins and gives no response or indicator suggesting how much long until completion.

**Comment by kastenk** [comment]
The iOS app has the same result - just spins, no export.  If I click on Excel or Markdown I get a response and actionable menus appear, but not with the pptx save functionality.

**Comment by kastenk** [comment]
This was for trying export more than 5 songs at once

**Comment by rodydavis** [comment]
Looking into it!

**Comment by rodydavis** [comment]
Fixed on version 3, working on rolling out

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
