### ISSUE TITLE
#284 music and slides broken

### ISSUE THREAD

**Issue by headmasterditto** [hymns-for-worship/issues#88]
Probably pretty easy to fix amidst everything else but #284 seems to be down at the moment

**Comment by rodydavis** [comment]
Just rolling out the new update, it is switching to downloading the bundles for each hymn instead of streaming them (server was getting congested).

This also aligns presentation creator and the app to use the new v2 format.

**Comment by rodydavis** [comment]
Fixed on v3 https://hymnsforworship.app

Update for mobile and desktop will follow soon
