### ISSUE TITLE
Missing song

### ISSUE THREAD

**Issue by rhcavender** [hymns-for-worship/issues#89]
I believe song number 284 is missing!

Randy

**Comment by rodydavis** [comment]
Thanks for the find!

**Comment by rodydavis** [comment]
I have verified that it is there now!

<img width="1012" alt="Screenshot 2024-09-07 at 11 21 05 AM" src="https://github.com/user-attachments/assets/4aa5fa0c-69f8-4643-8200-4323a4d3faf4">
