### ISSUE TITLE
Problem restoring purchases

### ISSUE THREAD

**Issue by jgh450** [hymns-for-worship/issues#9]
I have clicked the restore purchases button repeatedly and still can't access the sheet music. I previously purchased the revised and supplement versions but both are still showing red like I haven't purchased them.

**Comment by 65fastback2plus2** [comment]
Same issue. I was able to cancel and renew my echoice subscription and get that one working but HFWR and HFWS won't restore or let you repurchase.

**Comment by rodydavis** [comment]
Can you check if it is fixed with the latest?
