### ISSUE TITLE
#538, #21567 -- Slide Generation

### ISSUE THREAD

**Issue by headmasterditto** [hymns-for-worship/issues#90]
Howdy. So far, everything in the newest version is looking and feeling pretty good. I've noticed on a couple of occasions now with the titular hymns that the slides are currently generating rather...interestingly.

#538's slides seem to be generating very out of order (e.g. after the title card, the first four music slides are slide 1, the last two slides in the song, then slide 2).

For #21567, it looks like the first verse is being included multiple times; it looks to me like maybe the first verse is being included in the chorus.

There's one or two other small things but they are probably better saved for their own report if anything. Keep on keeping on.

**Comment by rodydavis** [comment]
Definitely not supposed to happen! Does it happen every time or just sometimes?

**Comment by headmasterditto** [comment]
Thus far, every time. Just tested it now to be sure.

**Comment by rodydavis** [comment]
Can you include the exact steps to reproduce for a song?

**Comment by headmasterditto** [comment]
Just adding the song to a playlist and exporting, I haven't done any special alterations to either one. If it'll help, here's the playlist URLs and the resulting exports as well:
- [31 Jan.](https://hymnsforworship.app/#/users/088xkoplrzajei7/playlists/000000-sNQa2z9c) corresponds to #21567
- [3 Feb.](https://hymnsforworship.app/#/users/088xkoplrzajei7/playlists/000000qEzLx_lOL) corresponds to #538
[3 Feb 2024 am.pptx](https://github.com/hymns-for-worship/issues/files/14250655/3.Feb.2024.am.pptx)
[31 Jan 2024.pptx](https://github.com/hymns-for-worship/issues/files/14250657/31.Jan.2024.pptx)

**Comment by DSCOBURN** [comment]
This was corrected today
