### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by jerickson1075** [hymns-for-worship/issues#91]
On MacOS and iOS, playlist syncing does not work unless all devices are on and the app open at the time of changes to any playlist.

**Comment by rodydavis** [comment]
Oh interesting! That is definitely not intentional. Will look into it 👍🏼

**Comment by jerickson1075** [comment]
Thanks so much!

**Comment by joescarborough** [comment]
I have the same problem except it never resolves.

**Comment by rodydavis** [comment]
Can you test with https://hymnsforworship.app?

V4 fixes sync after many many hours of testing and research

**Comment by jerickson1075** [comment]
Rody,

Thank you so much for your hard work to the glory of the Lord!

I cannot access version 4.  It might be due to the fact that I'm now on
beta releases on all of my Apple devices?

Please see the attachments.

Br,
James E.

**Comment by rodydavis** [comment]
Attachments do not show if you respond to the email, only if you add them on the GitHub issue!

And beta is on iOS and out for the web!

**Comment by rodydavis** [comment]
V4 fixes this, and is out everywhere except macos, still working with app store review on it
