### ISSUE TITLE
Adding to Playlists 

### ISSUE THREAD

**Issue by jerickson1075** [hymns-for-worship/issues#92]
If I’m searching hymns in the hymns tab, how do I add hymns to playlists?  It seems the only way to add to playlists is from the playlist tab. I need to preview songs before I pick them. So, adding to playlists from within the song itself is ideal.

**Comment by rodydavis** [comment]
Working on adding that functionality back!

**Comment by jerickson1075** [comment]
Thank you!!

**Comment by rodydavis** [comment]
Added on version 4!
