### ISSUE TITLE
Pro plan subscription issue - Windows

### ISSUE THREAD

**Issue by vaughanje** [hymns-for-worship/issues#93]
I reported this in email a couple weeks ago. Thought I might try posting it here.

On Feb 2, I purchased an Annual Pro subscription using Apply Pay on my iPhone. (But I was logged into the app with a separate id - admin@timberlandchurch.org)

On my phone, I can see slides for songs in eChoice, which make it appear that the payment worked, and it shows me subscribed in my account settings. 

![image](https://github.com/hymns-for-worship/issues/assets/9681424/94a8177f-fb1f-4ad9-86a2-bf7d35b21e42)

But when I open the app on my Windows laptop (using the same account), It tells me I need to purchase on a mobile account and be logged in to the same account, which I have done.  It shows Not subscribed under my account settings. 

![image](https://github.com/hymns-for-worship/issues/assets/9681424/1bd9b7d3-ef98-4993-8e64-5d21d7869fe8)

![image](https://github.com/hymns-for-worship/issues/assets/9681424/b5f020e5-c7c4-4d42-a5e1-2622c57c52ba)

Thanks for any help you can provide!
Eric Vaughan

**Comment by joescarborough** [comment]
I too have this issue.

**Comment by rodydavis** [comment]
Still trying to get to the bottom of this bug! Actively working on it 👍🏼

**Comment by dleehend** [comment]
Just want to add that I have this issue also. Just purchased annual pro subscription to try to overcome failure to access previous lifetime purchase. Did a playlist and export on my phone. Opened app in Chrome on Windows 11 and it says I have no subscription just like original post.

**Comment by rodydavis** [comment]
Actively working on it! There is an issue for some people but not all. Pretty sure I have a fix and will role it out when verified

**Comment by rodydavis** [comment]
Can you test with https://hymnsforworship.app?

Windows app should be updated too

**Comment by dleehend** [comment]
Clicked your link. Selected a song. Logged in. Got this screenshot. Same
result for slides. Tried several songs with same result
Dan

[image: Screenshot 2024-07-13 173543.png]

**Comment by dleehend** [comment]
Rody,

Just tried the windows app. Fresh download from microsoft. Same result. No
music or slides, just the three 'Can' statements.
Dan

**Comment by dleehend** [comment]
Rody,

One more time. I used the same log in that works fine on android. The
windows app and online app show my eChoice purchases from the RJ Stevens
site. But they do not show my subscription or earlier lifetime purchase
from Google Play.
Dan

**Comment by rodydavis** [comment]
Working on getting Android to sync properly on the backend for purchases. But that is wonderful the website purchases are there.

I will see if I can get the backend to show the purchases correctly. The web and windows one will just need to be reopen and be up to date when the fix is out.

**Comment by dleehend** [comment]
I'll try again on Monday or late Sunday evening unless you thing I should
wait longer for the update to go through.
Dan

**Comment by rodydavis** [comment]
Should be stable in 2 weeks after testing!

**Comment by rodydavis** [comment]
Fully rolled out on 4.0.0!

**Comment by joescarborough** [comment]
I have issues. I'll try to post them up tomorrow.

Joe Scarborough
713-472-7403 - cell
***@***.***
