### ISSUE TITLE
Search not working correctly.  It can find "Jesus, draw" but not "Jesus draw"  (no quotes used when searching).   Appears to be an issue with all hymn titles that have commas.

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#94]
![image](https://github.com/hymns-for-worship/issues/assets/10003118/da8dc5c7-8f8b-4597-9954-42833d8d764b)

**Comment by rodydavis** [comment]
This is a tough one, I implemented Full Text Search and and it would support this, but the second it was an invalid query it would return nothing, this is a fuzzy search which is more flexible but not with punctuation.

I am working on trying to combine the two results but trying to nail the UX.

**Comment by rodydavis** [comment]
Can you test with https://hymnsforworship.app?

Added lyrics search back
