### ISSUE TITLE
Lifetime Sheet Music No Longer Working

### ISSUE THREAD

**Issue by SL003** [hymns-for-worship/issues#97]
Version: 3.2.0+766

Since a recent update, I’m not able to access the lifetime sheet music via the iOS app. (Hymns for Worship (Revised) and Hymns for Worship (Supplement)) I’ve tried opening the app on an iPhone and iPad. Also from the settings, I see the Server Status continuously spinning. 

I’ve tried logging out/in and restoring purchases. I’ve also tried purchasing the music again. I get a message that I already made the purchase. Nothing changes, I still can’t see the sheet music or slides. 
![IMG_9248](https://github.com/hymns-for-worship/issues/assets/163936496/31e6fbe7-6fa4-42f8-b156-39b01721ff10)

**Comment by rodydavis** [comment]
Working on the fix, the purchases are still safe!

**Comment by rodydavis** [comment]
Fixed on version 4.0.0
