### ISSUE TITLE
Add hymn SKU as searchable field in app and studio

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#98]
Add hymn SKU as searchable field in app and studio.  Eg: 

RJSEC21819
RJSEC21820
RJSEC21821
RJSEC21822

And ensure multiple SKUs can be entered in search bar for multi-select.

**Comment by rodydavis** [comment]
Are you meaning you want to add a comma separated list and it auto select them?

"RJSEC21819,RJSEC21820,RJSEC21821,RJSEC21822" <-- in the search box

**Comment by ebizman** [comment]
That was also be nice but right now, search for a single SKU does not work. 
 

-Rhett

**Comment by rodydavis** [comment]
SKU search added to the app!

**Comment by rodydavis** [comment]
Yeah I added but forgot I did not add it back after switching the search to filters. I'll do it on the next round of updates

**Comment by rodydavis** [comment]
Removed SKU search, but you can search by hymn number instead
