### ISSUE TITLE
HFW app (Edge browser on MacOS) killing CPU

### ISSUE THREAD

**Issue by ebizman** [hymns-for-worship/issues#99]
See screenshot.   Closing the HFW app returns to normal CPU usage.   Note swirl in upper right corner - it never stops.   

Microsoft Edge
Version 122.0.2365.92 (Official build) (x86_64)

Would be helpful to allow selection of the version text in Settings: 
<img width="147" alt="image" src="https://github.com/hymns-for-worship/issues/assets/10003118/7e91cd67-f70b-44fc-b30c-1fc5173461e4">

<img width="1440" alt="image" src="https://github.com/hymns-for-worship/issues/assets/10003118/125076d9-ec1b-4dbf-a047-618b5771faf7">

**Comment by rodydavis** [comment]
Made the change, in a future version the version can be selected.

That is weird that it is using so much CPU. I am working on offline improvements so it doesnt have to connect to the server on startup which the loading indicator is showing.

**Comment by rodydavis** [comment]
v4 fixes this too!
